/* ============ DATA — Saigon Fashion Directory ============
   Single source of truth for the businesses listed on fashion-directory
   and routed by the planner (js/route-panel.js). Edit here, nowhere else.
   st: walk|appt|online|hub|popup  · tier: mid|premium|luxury|couture|none
   city: SGN|HAN|VN|INTL · cat: women|men|luxury|tailor|active|access|sleep|market */
window.SS_DIRECTORY=[
/* — Contemporary womenswear · Saigon walk-ins — */
{n:"Huelley Rose",h:"huelleyrose",cat:"women",city:"SGN",area:"D1 · Tân Định",tier:"premium",st:"walk",a:"214 Hai Bà Trưng",no:"Romantic RTW; worldwide shipping. Shares its building with Huelley & Stress Mama."},
{n:"Huelley",h:"",w:"https://huelley.com/",cat:"women",city:"SGN",area:"D1 · Tân Định",tier:"premium",st:"walk",a:"214 Hai Bà Trưng",no:"Sister label to Huelley Rose. 8:30–21:40."},
{n:"Stress Mama",h:"stress.mama",cat:"women",city:"SGN",area:"D1 · Tân Định",tier:"mid",st:"walk",a:"214 Hai Bà Trưng · Vincom Đồng Khởi · Thảo Điền",a2:1,no:"Playful streetwear; 3 locations across the city."},
{n:"Dawn Vintage",h:"dawnavintage",cat:"women",city:"SGN",area:"D1 · Bến Nghé",tier:"mid",st:"walk",a:"2F, 42 Tôn Thất Thiệp",no:"Curated vintage inside the 42 TTT multi-brand building.",fib:["circular"]},
{n:"1998 Before The Dawn",h:"1998beforethedawn",cat:"women",city:"SGN",area:"D1 · Bến Nghé",tier:"mid",st:"walk",a:"2F, 42 Tôn Thất Thiệp",no:"Vintage; pairs with Dawn Vintage. 10:00–21:00.",fib:["circular"]},
{n:"Depass",h:"depass.store",cat:"women",city:"SGN",area:"D1 · Bến Nghé",tier:"mid",st:"walk",a:"Rm 38E, 1F, 42 Tôn Thất Thiệp",no:"Local label in the 42 TTT building."},
{n:"Mangata",h:"mangata.vn",cat:"women",city:"SGN",area:"D1",tier:"premium",st:"walk",a:"1F, 40E Ngô Đức Kế",no:"Founder-run; has a sister coffee brand, Blubean."},
{n:"Josephine",h:"josephineofficial.vn",cat:"women",city:"SGN",area:"D1 · Bến Thành",tier:"premium",st:"walk",a:"106A Lê Thị Riêng",no:"Feminine RTW; also a Hanoi branch on Phố Huế."},
{n:"LSOUL",h:"lsoul.officiel",cat:"women",city:"SGN",area:"D1",tier:"premium",st:"walk",a:"257B Nguyễn Trãi",no:"Well-known minimalist label. 9:30–21:30."},
{n:"Jubin Studio",h:"jubinstudio",cat:"women",city:"SGN",area:"D1 · Đa Kao",tier:"mid",st:"walk",a:"4B Phan Kế Bính",w:"https://global.jubinstudio.com/",no:"“The perfect wardrobe for petite girls.”"},
{n:"Moodswings",h:"moodswingsvn",cat:"women",city:"SGN",area:"D1 · Tân Định",tier:"mid",st:"walk",a:"75E Đặng Dung",no:"10:00–21:30; worldwide shipping."},
{n:"CEM — Chị Em Mình",h:"cem_club",cat:"women",city:"SGN",area:"D1 · Bến Thành",tier:"mid",st:"walk",a:"26 Ký Con",no:"Vietnam-based; worldwide shipping."},
{n:"Pomelo Flower",h:"pomelo.flower",cat:"women",city:"SGN",area:"D1",tier:"premium",st:"walk",a:"245/43 Nguyễn Trãi",no:"“Timeless fashion for ladies,” made in Saigon."},
{n:"Clothes Bar",h:"clothesbar.vn",cat:"women",city:"SGN",area:"D1 · Bến Thành",tier:"premium",st:"walk",a:"149/19 Lê Thị Riêng",no:"“Be your own muse.” Also a Singapore pop-up."},
{n:"Jenéa by Jenny",h:"jeneabyjenny.official",cat:"women",city:"SGN",area:"D1 · Tân Định",tier:"premium",st:"walk",a:"380 Hai Bà Trưng",no:"Recently moved to this new location."},
{n:"Calista de Minh Thanh",h:"calistademinhthanh.official",cat:"women",city:"SGN",area:"D1",tier:"premium",st:"walk",a:"265 Lý Tự Trọng",no:"Also stocked on MEAN BLVD. Next to Enuff."},
{n:"Enuff Studio",h:"enuffstudiobyst",cat:"women",city:"SGN",area:"D1 · Bến Thành",tier:"premium",st:"walk",a:"261 Lý Tự Trọng",no:"HCMC-based; worldwide shipping."},
{n:"Goût De Jun",h:"goutdejun.ig",cat:"women",city:"SGN",area:"D1 / D3",tier:"premium",st:"walk",a:"55 Nguyễn Trãi + 1 Trần Quang Diệu + TNP",no:"Three points of sale across the centre."},
{n:"Hoang Studios",h:"hoangstudios",cat:"women",city:"SGN",area:"D1 · Bến Thành",tier:"mid",st:"walk",a:"41 Nguyễn Trãi",no:"Sparse online presence — check it's still trading as fashion before you go.",flag:1},
{n:"De Pure",h:"depure.offical",cat:"women",city:"SGN",area:"D1",tier:"premium",st:"appt",a:"21 Đặng Thị Như — opening soon",no:"Store “coming soon”; online meanwhile. Faces Daphale."},
{n:"Arya",h:"arya.theofficial",cat:"women",city:"SGN",area:"D1 / D3 · hubs",tier:"premium",st:"hub",a:"386 Concept + Daspace, 46/13 Trần Quý Khoách (D1 · Tân Định)",no:"Sold via multi-brand hubs; no standalone store."},
{n:"Babie Club",h:"babieclub_wear",cat:"women",city:"SGN",area:"D1 · hubs",tier:"mid",st:"hub",a:"The New Playground + 11 Garmentory",no:"Sun-ready shorts & daily wear via two hubs."},
{n:"Elena NGN",h:"elena.ngn",cat:"women",city:"SGN",area:"D1 · Đa Kao",tier:"premium",st:"hub",a:"Stocked at Rue Miche, 9B Phùng Khắc Khoan",no:"“Flowers on men.” Own Hanoi store closed."},
{n:"Teddy And",h:"teddyand",cat:"women",city:"SGN",area:"D1 · Đồng Khởi",tier:"premium",st:"popup",a:"Pop-up @ Rue Miche L'Édition, 171 Đồng Khởi",no:"Summer pop-up — check IG it's still running."},

{n:"Whose Studio",h:"whose.studio",cat:"women",city:"SGN",area:"D3 · P.14",tier:"mid",st:"walk",a:"386/15 Lê Văn Sỹ",no:"“New home” — recently relocated. 10:00–21:00."},
{n:"Firefly Studio",h:"firefly_studio.vn",cat:"women",city:"SGN",area:"D3 · Nhiêu Lộc",tier:"premium",st:"walk",a:"816/24 Trường Sa",no:"Has a swim line (FFSD). 10:30–21:30."},
{n:"Daniv Dear",h:"daniv.dear",cat:"women",city:"SGN",area:"D3 · P.2",tier:"mid",st:"walk",a:"4F, 563/32 Nguyễn Đình Chiểu",no:"Coquette-leaning RTW. 10:00–21:00."},
{n:"Résel Studio",h:"resel.stu",cat:"women",city:"SGN",area:"D3",tier:"premium",st:"walk",a:"245 Võ Văn Tần",no:"Slow fashion, in-house production; Bangkok branch too."},
{n:"Résel Bridal",h:"resel.bridal",cat:"luxury",city:"SGN",area:"D3",tier:"couture",st:"appt",a:"245 Võ Văn Tần",no:"Private 1:1 bridal fittings, by appointment."},
{n:"Moulin Rose",h:"moulinrose.stu",cat:"women",city:"SGN",area:"D3 · P.14",tier:"premium",st:"walk",a:"48 Trần Quang Diệu",no:"On the Trần Quang Diệu design strip."},
{n:"Tartan Studios",h:"tartan_studios",cat:"women",city:"SGN",area:"D3",tier:"premium",st:"walk",a:"70 Trần Quang Diệu",no:"“What creates you creates happiness.”"},
{n:"Sassy Sis",h:"sassysis_br",cat:"women",city:"SGN",area:"D3 · P.5",tier:"mid",st:"walk",a:"441/36 Nguyễn Đình Chiểu",no:"10:00–20:30 daily."},
{n:"So Dópe Club",h:"sodope.club",cat:"women",city:"SGN",area:"D3 · P.5",tier:"premium",st:"walk",a:"1F, 353 Võ Văn Tần + 97 Trần Quang Diệu",no:"Streetwear-leaning; two D3 doors."},
{n:"18 Again",h:"18again.official",cat:"women",city:"SGN",area:"D3 · P.14",tier:"mid",st:"walk",a:"52 Trần Quang Diệu",no:"Orders routed via @eighteen.loveyou for now. 10:00–21:45.",flag:1},
{n:"BaaBeeBoo",h:"baabeeboo.club",cat:"women",city:"SGN",area:"D3 · P.14",tier:"mid",st:"walk",a:"2F, 6 Trần Quang Diệu",no:"Above Kathy Atelier. 13:30–21:00."},
{n:"Lace Lingerie Lover",h:"lace.lingerielover",cat:"women",city:"SGN",area:"D3 · Nhiêu Lộc",tier:"premium",st:"walk",a:"48 Trần Quang Diệu",no:"Lingerie; worldwide shipping."},
{n:"Chérieon",h:"cherieon_official",cat:"women",city:"SGN",area:"D3 / D1",tier:"premium",st:"walk",a:"76 Trần Quang Diệu + Vincom Đồng Khởi B2",no:"“Heaven dress in temptation.”"},
{n:"caleélilou",h:"caleelilou.studio",cat:"women",city:"SGN",area:"D3",tier:"premium",st:"appt",a:"136/5 Trần Quang Diệu",no:"Softly feminine; fitting by appointment."},
{n:"La Vierge",h:"lavierge.vn",cat:"women",city:"SGN",area:"D3 · P.5",tier:"premium",st:"walk",a:"225/6 Nguyễn Đình Chiểu",no:"/lavjɛʁʒ/ Where every touch ignites desire. Ships worldwide."},
{n:"Chan Club",h:"chanclub.vn",cat:"women",city:"SGN",area:"D3 · P.14",tier:"mid",st:"walk",a:"154 Trần Quang Diệu",no:"Based in Việt Nam, ships worldwide. Các sản phẩm bên shop là hàng thiết kế và tự sản xuất — không bán trên sàn thương mại điện tử."},
{n:"Rêver",h:"rever.clothings",cat:"women",city:"SGN",area:"D3 · P.14",tier:"mid",st:"walk",a:"91 Trần Quang Diệu",no:"New drop weekly."},
{n:"Mooris",h:"moorisclothing",cat:"luxury",city:"SGN",area:"D3 · P.5",tier:"luxury",st:"walk",a:"234 Võ Văn Tần, P.5, Q.3",no:"DM for orders — ships worldwide. Hotline +84 765 793 515."},

{n:"11 Garmentory",h:"11garmentory",cat:"women",city:"SGN",area:"Phú Nhuận",tier:"premium",st:"hub",a:"117B Nguyễn Đình Chính, P. Cầu Kiệu, Phú Nhuận",no:"Multi-brand creative hub + café. 10:00–21:30."},
{n:"Duu Stu",h:"duu.stu",cat:"women",city:"SGN",area:"Phú Nhuận",tier:"premium",st:"hub",a:"117B Nguyễn Đình Chính, P. Cầu Kiệu, Phú Nhuận",no:"“Lazy but chic” flagship — ground floor, 11 Garmentory."},
{n:"Badchoices",h:"badchoices.vn",cat:"women",city:"SGN",area:"Phú Nhuận",tier:"mid",st:"hub",a:"117B Nguyễn Đình Chính, P. Cầu Kiệu, Phú Nhuận",no:"Booth @ 11 Garmentory. “Bad choices make good stories.”"},
{n:"Moon Me",h:"moon_me.studio",cat:"women",city:"SGN",area:"Phú Nhuận",tier:"mid",st:"walk",a:"330/1D Phan Đình Phùng",no:"Upcycled/custom 2nd-hand; opened May 2026.",fib:["circular"]},
{n:"L'Espoir",h:"lespoir.com.vn",cat:"women",city:"SGN",area:"Phú Nhuận",tier:"premium",st:"walk",a:"489A/4 Huỳnh Văn Bánh",no:"9:30–22:00; nationwide COD."},
{n:"By Vee",h:"byvee.style",cat:"women",city:"SGN",area:"Phú Nhuận",tier:"mid",st:"walk",a:"50 Trần Huy Liệu",no:"9:00–22:00; cheaper in-store than Shopee."},
{n:"Tiela",h:"tiela.official",cat:"women",city:"SGN",area:"Phú Nhuận",tier:"premium",st:"walk",a:"42 Trần Huy Liệu",no:"“Made for your inner muse.” 9:00–22:00."},
{n:"Chou Chou",h:"__chouchou.official",cat:"women",city:"SGN",area:"Phú Nhuận",tier:"mid",st:"walk",a:"100A5 Thích Quảng Đức + 324 Huỳnh Văn Bánh",no:"Two Phú Nhuận branches."},
{n:"The Fancé",h:"thefance.official",cat:"women",city:"SGN",area:"Phú Nhuận",tier:"premium",st:"walk",a:"111C Hoa Lan + 11 Garmentory",no:"Also a Hanoi floor at Lotte Center."},
{n:"Nosbyn Studio",h:"nosbyn_studio",cat:"women",city:"SGN",area:"Thủ Đức · Thảo Điền",tier:"premium",st:"walk",a:"06 Đặng Hữu Phổ",no:"10:00–20:00 daily; worldwide shipping."},
{n:"The Country Boutiques",h:"thecountry_boutiques",cat:"women",city:"SGN",area:"Q5 · Chợ Lớn",tier:"premium",st:"walk",a:"2F, 123 Trần Hưng Đạo",no:"Worldwide delivery."},
{n:"Glamdoll",h:"glamdoll_0fficial",cat:"women",city:"SGN",area:"Tân Bình",tier:"mid",st:"walk",a:"346 Lê Văn Sỹ",no:"Long-running local RTW."},

/* — Chains — */
{n:"OLV",h:"olv.officiel",cat:"women",city:"SGN",area:"Nationwide · 24 stores",tier:"premium",st:"walk",a:"Flagship 127–129 Nguyễn Trãi, D1",no:"24 stores VN-wide; see olv.vn/pages/our-stores."},
{n:"Joven",h:"joven.fashion",cat:"women",city:"SGN",area:"HCMC · 9 stores",tier:"mid",st:"walk",a:"joven.vn store locator",no:"9 stores across HCMC."},
{n:"IVY moda",h:"ivy_moda",cat:"women",city:"SGN",area:"Nationwide chain",tier:"premium",st:"walk",a:"ivymoda.com/page/cuahang",no:"Major nationwide womenswear chain."},
{n:"LAVIEM",h:"laviemvn",cat:"women",city:"SGN",area:"HCMC + Hanoi",tier:"premium",st:"walk",a:"289 Võ Văn Tần (HCMC) +4 more",no:"5 stores incl. Hanoi & Thái Nguyên."},
{n:"Hapas",h:"hapas.vn",cat:"women",city:"SGN",area:"Multi-branch",tier:"mid",st:"walk",a:"hapas.vn/pages/dia-diem-cua-hang",no:"“Pretty Normal” everyday chain."},

/* — Menswear & streetwear · Saigon — */
{n:"DirtyCoins",h:"dirtycoins.vn",cat:"men",city:"SGN",area:"D1 · Bến Nghé",tier:"mid",st:"walk",a:"The New Playground, 26 Lý Tự Trọng",a2:1,price:"tees 300–700k₫",no:"Arguably Vietnam's biggest streetwear name — heavy branding, hip-hop-adjacent. Destination flagship at 561 Sư Vạn Hạnh (D10); also TNP @ Vincom Đồng Khởi, Grand Park & Aeon Bình Tân. 9:00–22:00."},
{n:"ICONDENIM",h:"icondenim.official",cat:"men",city:"SGN",area:"D1 · Bến Thành",tier:"mid",st:"walk",a:"12–12bis Cách Mạng Tháng 8 + 261 Nguyễn Trãi",a2:1,price:"jeans 500–700k₫",no:"Denim-first men's casual chain — one of HCMC's largest local menswear retailers; 13 city stores (D7, Tân Phú, Bình Thạnh…). 8:30–22:00."},
{n:"Degrey",h:"degrey.official",cat:"men",city:"SGN",area:"Phú Nhuận",tier:"mid",st:"walk",a:"24 Hồ Biểu Chánh",a2:1,no:"Gen-Z streetwear mixing Vietnamese cultural motifs; also 67–69 Đường D10 (Tân Phú) + 382D Trần Hưng Đạo (D5 · Chợ Lớn)."},
{n:"Bad Habits",h:"badhabitsstore.vn",cat:"men",city:"SGN",area:"D1 · Bến Thành",tier:"mid",st:"walk",a:"22 Lê Thị Riêng + 42 Tôn Thất Thiệp + TNP",a2:1,no:"Saigon unisex streetwear (est. 2017) with Vietnamese-culture graphics; 4th door at 2 Trần Huy Liệu, Phú Nhuận. Also Hanoi, Cần Thơ & Bangkok."},
{n:"HADES Studio",h:"hades.studio",cat:"men",city:"SGN",area:"D1 / D3",tier:"mid",st:"walk",a:"B1 Vincom Đồng Khởi + 152 Trần Quang Diệu",a2:1,no:"First-wave VN streetwear — darker, grunge-leaning design language. (Older lists citing Gò Vấp/Phạm Ngũ Lão branches are stale.)"},
{n:"Routine",h:"routine_official",cat:"men",city:"SGN",area:"Gò Vấp",tier:"mid",st:"walk",a:"523A Quang Trung",a2:1,price:"400–800k₫",no:"Menswear-rooted, now VN's benchmark for office-to-weekend basics; 1,000 m² keystone store (May 2025) + Aeon Bình Tân & Tân Phú Celadon malls. 9:00–22:00 daily.",flag:1},
{n:"Aristino",h:"aristino_official",cat:"men",city:"SGN",area:"D1 · Đồng Khởi",tier:"premium",st:"walk",a:"L2-17, Vincom Đồng Khởi, 72 Lê Thánh Tôn",a2:1,price:"shirts 700k–1.5M₫",no:"K&G's premium men's brand — sharp shirts, polos & suiting-adjacent smart-casual; 30+ HCMC showrooms (Crescent Mall, Vincom Gò Vấp, D3/D5/Tân Bình). Mall showrooms 9:00–22:00."},
{n:"Môi Điên",h:"moidienstudio",cat:"men",city:"SGN",area:"D1 · Bến Nghé",tier:"premium",st:"walk",a:"28 Tôn Thất Thiệp",price:"~1–3M₫",no:"Tom Trandt's cult experimental label — deconstructed tailoring, upcycling, unisex statement pieces. Call ahead ☎ 090 395 12 12.",flag:1,fib:["circular"]},
{n:"Cao Minh Saigon",h:"caominh1948",cat:"men",city:"SGN",area:"D1",tier:"luxury",st:"appt",a:"74/6 Hai Bà Trưng",a2:1,price:"from ~14M₫",no:"Vietnam's oldest tailoring house (est. 1948) — the prestige choice; heritage atelier villa at 193/13 Điện Biên Phủ, Bình Thạnh by appointment. ~9:00–18:00, reservations recommended."},
{n:"SIR Tailor",h:"sirtailorvn",cat:"men",city:"SGN",area:"D1 · Đa Kao",tier:"premium",st:"appt",a:"207F Nguyễn Văn Thủ",price:"from 7.9M₫",no:"Modern gentleman's atelier since 2013 — full-canvas suits from 7.9M₫ (Asian cloth) / 16.9M₫ (Italian). Fittings by appointment; 21–30 day turnaround, minimum two fittings."},
{n:"H&D Tailor",h:"",cat:"men",city:"SGN",area:"D1 · Bến Thành",tier:"premium",st:"walk",a:"Store No. 5, New World Saigon Hotel arcade, 76 Lê Lai",price:"from ~6.5M₫",no:"Third-generation master tailor Tạ Quốc Hưng — an expat & business-traveler standby for 20 years; tropical-weight wools a specialty. Mon–Sat ~9:00–19:00.",flag:1},

/* — Luxury & couture (Saigon) — */
{n:"Le Thanh Hoa",h:"lethanhhoa_bridal",cat:"luxury",city:"SGN",area:"D1 · Bến Thành",tier:"couture",st:"appt",a:"67 Sương Nguyệt Ánh",no:"Dresses Miss Universe VN; evening + bridal. Hanoi branch too."},
{n:"Chung Thanh Phong",h:"chungthanhphongbridal",cat:"luxury",city:"SGN",area:"D1",tier:"couture",st:"appt",a:"189/1B Cống Quỳnh",no:"VN's celebrity wedding-dress name."},
{n:"Phan Huy",h:"phanhuy.official",cat:"luxury",city:"SGN",area:"Tân Bình",tier:"couture",st:"appt",a:"Showroom, Tân Bình (DM to book)",no:"Jan 2026: first Vietnamese on the official Paris Haute Couture calendar."},
{n:"SIXDO",h:"sixdovn",cat:"luxury",city:"SGN",area:"D1 · 12 HCMC stores",tier:"premium",st:"walk",a:"Flagship 147 Đồng Khởi (+11 more)",no:"Đỗ Mạnh Cường's diffusion RTW chain — feminine floral dresses at scale. (His couture is the separate DMC label.)"},
{n:"Valenciani",h:"valenciani1",cat:"luxury",city:"SGN",area:"D1",tier:"luxury",st:"walk",a:"26 Lý Tự Trọng",no:"Adrian Anh Tuấn's floaty, ultra-feminine gowns & resort — a red-carpet fixture."},
{n:"VUNGOC&SON",h:"vungocsonofficial",cat:"luxury",city:"SGN",area:"D1",tier:"luxury",st:"walk",a:"85 Lê Thánh Tôn",no:"Vietnam's colourful duo — vivid, opulent red-carpet gowns for beauty queens."},
{n:"Đỗ Long",h:"dolongofficial",cat:"luxury",city:"SGN",area:"D3 · Bàn Cờ",tier:"luxury",st:"walk",a:"442 Võ Văn Tần",no:"High-end women's RTW + evening gowns for celebs & pageant queens."},
{n:"Linh Nga Couture",h:"linhngacouture",cat:"luxury",city:"SGN",area:"D3 · Võ Thị Sáu",tier:"couture",st:"appt",a:"284A Nam Kỳ Khởi Nghĩa",no:"Haute-couture wedding gowns + heritage eveningwear; also a Hanoi flagship."},
{n:"LI LAM / LAM",h:"lamboutiquevn",cat:"luxury",city:"SGN",area:"D1 / D7",tier:"luxury",st:"walk",a:"71 Mạc Thị Bưởi + 76A Lê Lợi + Crescent Mall",no:"Minimalist, sensual, fluid womenswear; the layered organza Timeless skirt."},
{n:"GIA Studios",h:"gia_studios",cat:"luxury",city:"SGN",area:"D1",tier:"luxury",st:"walk",a:"125 Hai Bà Trưng",no:"Lâm Gia Khang's quiet luxury — craft-driven minimalism; stocked at Lane Crawford & Farfetch."},
{n:"Fancì Club",h:"fanci.club",cat:"luxury",city:"SGN",area:"Thủ Đức · Thảo Điền",tier:"luxury",st:"walk",a:"186 Nguyễn Văn Hưởng",no:"Cult Y2K corsetry & rosette dresses; worn by Bella Hadid, Hailey Bieber, BLACKPINK. 10:00–21:00."},
{n:"Minh Tuan Couture",h:"ntk_minhtuan.nguyen",cat:"luxury",city:"SGN",area:"Gò Vấp",tier:"couture",st:"appt",a:"416/39/13 Dương Quảng Hàm",no:"The beauty-queens' designer — hand-beaded gowns & national costumes (H'Hen Niê)."},
{n:"Nguyễn Hoàng Tú",h:"nguyenhoangtuofficial",cat:"luxury",city:"SGN",area:"By appointment",tier:"luxury",st:"appt",a:"Appointment / DM — no public address",no:"Conceptual artisanal womenswear, sculptural hand-sewing; relaunched May 2026. Confirm address by DM."},
{n:"Metiseko",h:"metiseko",cat:"luxury",city:"SGN",area:"D1 · Sài Gòn ward",tier:"premium",st:"walk",a:"157 Đồng Khởi",no:"Sustainable print-driven organic-cotton & natural-silk resort wear; controls its whole supply chain. Also Hội An & Hanoi. 8:30–21:30.",fib:["cotton","silk"]},
{n:"CAOSTU",h:"caostu.official",cat:"luxury",city:"SGN",area:"D3 · Nhiêu Lộc",tier:"premium",st:"walk",a:"7/5 Kỳ Đồng + Vincom Đồng Khởi B1",no:"Sculptural layered construction, signature metal eyelets; gender-neutral."},
{n:"Subtle Le Nguyen",h:"subtlelenguyen",cat:"luxury",city:"SGN",area:"D1 · via Rue Miche",tier:"premium",st:"hub",a:"Stocked at Rue Miche + L'Édition",no:"Minimalist contemporary womenswear; own showroom in Hanoi. HCMC = stockist only."},
{n:"La Phạm",h:"laphamdesign",cat:"luxury",city:"HAN",area:"Hanoi",tier:"luxury",st:"walk",a:"3F, 125D Lò Đúc",no:"Indigenous-fibre luxury — hemp, pandan, hand-dyed brocade + ethnic-minority craft; Paris/London FW. Online/appt for Saigon.",fib:["hemp"]},
{n:"Rue Des Chats",h:"ruedeschats",cat:"luxury",city:"HAN",area:"Hanoi · Hoàn Kiếm",tier:"premium",st:"walk",a:"2 Cổ Tân, Tràng Tiền",no:"Romantic Eurasian RTW with an upstairs tea salon (designer Anhuong Tran)."},

/* — Áo dài, tailors & craft (Saigon) — */
{n:"Áo Dài Võ Việt Chung",h:"",cat:"tailor",city:"SGN",area:"D3 · Bàn Cờ",tier:"luxury",st:"walk",a:"241–243 Nguyễn Đình Chiểu",no:"30-year veteran couturier; luxury áo dài & silk gala wear for celebrities and queens.",fib:["silk"]},
{n:"Thuy Design House",h:"thuydesignhouse",cat:"tailor",city:"SGN",area:"D1",tier:"luxury",st:"walk",a:"44B Lý Tự Trọng",no:"VN's most famous artistic áo dài designer; painterly brocades."},
{n:"KINZU (Áo Dài Song Toàn)",h:"",cat:"tailor",city:"SGN",area:"D3 · P.14",tier:"premium",st:"appt",a:"460 Lê Văn Sỹ",no:"Fully made-to-measure áo dài; ~3.7–20M₫, 2–3 wks. ☎ 0933 848 943."},
{n:"Le Saigonais",h:"",cat:"tailor",city:"SGN",area:"D1",tier:"premium",st:"walk",a:"1F, 77–79 Lý Tự Trọng",no:"Modern áo dài + concept store with café (dieuANH)."},
{n:"Thai Tuấn (silk)",h:"",cat:"tailor",city:"SGN",area:"D3",tier:"mid",st:"walk",a:"419–419A Hai Bà Trưng",no:"Silk & jacquard by the metre — bring it to a tailor.",fib:["silk"]},
{n:"Dòng Dòng Sài Gòn",h:"dongdongsg",cat:"tailor",city:"SGN",area:"Bình Thạnh",tier:"premium",st:"appt",a:"Workshop, Nguyễn Hữu Cảnh",no:"One-of-one bags from salvaged truck tarps — a great client gift.",fib:["circular"]},
{n:"SH Silk Embroidery",h:"",cat:"tailor",city:"SGN",area:"D3",tier:"premium",st:"appt",a:"114A/12 Trần Quốc Toản",no:"True hand-embroidered (thêu tay) áo dài & dresses."},
{n:"ManGii Custom Shoes",h:"",cat:"tailor",city:"SGN",area:"D1",tier:"premium",st:"walk",a:"228 Lê Thánh Tôn",no:"Handmade custom leather shoes incl. women's; ~800k–3M/pair."},
{n:"Dung Tailor",h:"",cat:"tailor",city:"SGN",area:"D1",tier:"mid",st:"walk",a:"221 Lê Thánh Tôn",no:"The classic “copy this garment exactly” shop; can finish in <3 days."},
{n:"Maydo Saigon",h:"",cat:"tailor",city:"SGN",area:"D1",tier:"premium",st:"appt",a:"1F, 130 Pasteur",no:"Best recent reviews for women's eveningwear made-to-measure."},
{n:"Duan Tailor",h:"",cat:"tailor",city:"SGN",area:"D3",tier:"premium",st:"appt",a:"465A Điện Biên Phủ",no:"Heritage bespoke + áo dài; 24–48h express line."},
{n:"A Dong Silk",h:"",cat:"tailor",city:"SGN",area:"Thủ Đức · Thảo Điền",tier:"mid",st:"walk",a:"23C Lê Văn Miến",no:"The famous Hội An tailor's Saigon branch; dresses ~$40–150."},

/* — Athleisure — */
{n:"Olaben",h:"olaben.official",cat:"active",city:"SGN",area:"Thảo Điền / D1",tier:"premium",st:"walk",a:"1M Đường số 10, Thảo Điền + 35 Nguyễn Trãi",no:"VN's flagship premium activewear; the Thảo Điền store has its own yoga/Reformer studio."},
{n:"EQL Apparel",h:"eql.apparel",cat:"active",city:"SGN",area:"D1/D3 edge",tier:"premium",st:"walk",a:"46 Võ Thị Sáu",no:"Saigon-born studio-to-street; also a Six Senses Côn Đảo boutique."},
{n:"Fitme",h:"fitme.sportswearvn",cat:"active",city:"SGN",area:"Bình Thạnh",tier:"mid",st:"walk",a:"308–310 Xô Viết Nghệ Tĩnh",no:"Owns its factory; “second-skin” fabrics."},
{n:"Thế Giới Đồ Tập",h:"",cat:"active",city:"SGN",area:"Nationwide · 20+",tier:"mid",st:"walk",a:"thegioidotap.vn locator",no:"Biggest local activewear chain (house brands ICADO/PAVO)."},
{n:"Shamdi",h:"",cat:"active",city:"SGN",area:"Phú Nhuận",tier:"mid",st:"walk",a:"217 Lê Văn Sỹ",no:"Lifetime product warranty; also Đà Nẵng, Nha Trang."},
{n:"Supersports",h:"",cat:"active",city:"SGN",area:"D7 / D1",tier:"premium",st:"walk",a:"Crescent Mall + 92–94 Nam Kỳ Khởi Nghĩa",no:"Authorized route to On Running & HOKA."},
{n:"REBN",h:"rebnofficial",cat:"active",city:"SGN",area:"Online",tier:"premium",st:"online",a:"rebnofficial.com",no:"Best online-only local pick; minimalist, cut for VN proportions."},

/* — Sun protection (UPF) · Saigon walk-ins — */
{n:"UV100",h:"",cat:"active",sub:"Sun protection",city:"SGN",area:"D1 / D3",tier:"mid",st:"walk",a:"46 Nguyễn Bỉnh Khiêm (D1) + 645 Nguyễn Đình Chiểu (D3)",a2:1,no:"ARPANSA-certified UPF 50+ — the measurable one. Taiwanese, distributed by Smarttex.",flag:1},
{n:"Hinlet",h:"",cat:"active",sub:"Sun protection",city:"SGN",area:"Tân Bình",tier:"mid",st:"walk",a:"340D Hoàng Văn Thụ",no:"Sun-resistant fashion since 2016.",flag:1},
{n:"MOMIU",h:"",cat:"active",sub:"Sun protection",city:"SGN",area:"Tân Phú",tier:"mid",st:"walk",a:"299 Thoại Ngọc Hầu",no:"The beloved local sun-jacket house.",flag:1},
{n:"TokyoLife",h:"",cat:"active",sub:"Sun protection",city:"SGN",area:"Tân Phú",tier:"mid",st:"walk",a:"683A Âu Cơ",no:"Japanese-tech UV “SunStop” shirts, UPF 50+ claimed. Also 73/4b Lê Văn Khương, D12 (outside the mapped zones).",flag:1},

/* — Accessories — */
{n:"SEESON",h:"seesonvn",cat:"access",sub:"Eyewear",city:"SGN",area:"D3 · Xuân Hòa",tier:"premium",st:"walk",a:"199 Điện Biên Phủ",no:"VN's leading frame designer; flagship has in-house optometry + café."},
{n:"The Purists Club",h:"tpceyewear",cat:"access",sub:"Eyewear",city:"SGN",area:"D1",tier:"luxury",st:"walk",a:"2F, 80 Lý Tự Trọng",no:"Collector-grade eyewear: Jacques Marie Mage, Kuboraum, Matsuda…"},
{n:"Ananas",h:"ananasvn",cat:"access",sub:"Shoes",city:"SGN",area:"D3 / D1 / Bình Thạnh",tier:"mid",st:"walk",a:"386/4 Lê Văn Sỹ + 41 Đặng Thị Nhu +2",no:"VN's top vulcanized-sneaker brand."},
{n:"Shondo",h:"shondo.official",cat:"access",sub:"Shoes",city:"SGN",area:"D3 / D5 · 13+ stores",tier:"mid",st:"walk",a:"203 Hai Bà Trưng + 66 Nguyễn Trãi",no:"Gen-Z sandals/sneakers/clogs."},
{n:"Vascara",h:"vascara.official",cat:"access",sub:"Shoes",city:"SGN",area:"Nationwide · 120+",tier:"mid",st:"walk",a:"Flagship 375–377 Nguyễn Đình Chiểu",no:"Polished women's work-wardrobe shoes & bags."},
{n:"Juno",h:"juno.vn",cat:"access",sub:"Shoes",city:"SGN",area:"Nationwide · 90+",tier:"mid",st:"walk",a:"248 Phan Đình Phùng + 360 Hai Bà Trưng",no:"Seedcom-backed; fast design turnover."},
{n:"CNES Shoemaker",h:"cnes_shoemaker",cat:"access",sub:"Shoes",city:"SGN",area:"D1 / Tân Bình",tier:"luxury",st:"walk",a:"75 Trần Đình Xu + 206 Lê Lai",no:"Goodyear-welted + bespoke since 1994; mostly men's."},
{n:"Chautfifth",h:"chautfifth",cat:"access",sub:"Bags",city:"SGN",area:"D3",tier:"premium",st:"walk",a:"288A7 Nam Kỳ Khởi Nghĩa",no:"Handcrafted structured handbags — the local designer-bag name of the moment."},
{n:"Curnon",h:"curnon.official",cat:"access",sub:"Watches",city:"SGN",area:"D3 · Nhiêu Lộc",tier:"mid",st:"walk",a:"348 Lê Văn Sỹ",no:"VN's first homegrown fashion-watch brand (2016)."},
{n:"Shimmer Silver",h:"shimmersilverjewelry",cat:"access",sub:"Jewelry",city:"SGN",area:"D1 · Bến Thành",tier:"mid",st:"walk",a:"128 Lê Lai",no:"Handmade silver + natural gemstones; VN motifs."},
{n:"AME Jewellery",h:"amejewelleryofficial",cat:"access",sub:"Jewelry",city:"SGN",area:"D1 · Đồng Khởi",tier:"luxury",st:"appt",a:"15F Vincom Center Đồng Khởi",no:"Bespoke gold/diamonds/pearls, by appointment; ships to 26 countries."},
{n:"Floralpunk",h:"floralpunk",cat:"access",sub:"Jewelry",city:"SGN",area:"D1 · Tân Định",tier:"premium",st:"walk",a:"31–33 Thạch Thị Thanh",no:"Julia Đoàn's cult accessories label — jewelry, bags, eyewear."},

/* — Sleep & loungewear · natural fibres first (market research, Jul 2026) — */
{n:"VINCY Homewear",h:"",w:"https://vincy.com.vn/",cat:"sleep",city:"SGN",area:"D1 · Tân Định",tier:"mid",st:"walk",a:"248 Hai Bà Trưng, P. Tân Định, Q.1",price:"sets ~240–740k₫",no:"Cotton/kate/tole homewear chain, 6 HCMC stores — skip the satin lines, buy the cotton. Hotline 7:00–21:30.",fib:["cotton"]},
{n:"ONOFF",h:"",w:"https://onoff.vn/",cat:"sleep",city:"SGN",area:"D1 · Tân Định",tier:"mid",st:"walk",a:"366 Hai Bà Trưng",no:"Cotton-first underwear & homewear chain (est. 2005) — sleepwear for women and men; 8 HCMC-area stores, live locator at onoff.vn.",flag:1,fib:["cotton"]},
{n:"Mialala",h:"",w:"https://mialala.vn/",cat:"sleep",city:"SGN",area:"D3",tier:"premium",st:"walk",a:"192 Cách Mạng Tháng 8, P.10, Q.3",no:"Lingerie + sleepwear house, 54 stores nationwide — ask for the cotton and đũi pieces; the “lụa” sets are synthetic satin.",flag:1,fib:["cotton"]},
{n:"Metiseko",h:"",w:"https://metiseko.com/",cat:"sleep",sub:"Silk & lounge line",city:"SGN",area:"D1 · Bến Nghé",tier:"luxury",st:"walk",a:"157 Đồng Khởi, P. Bến Nghé, Q.1",no:"Mulberry silk + organic cotton, printed in-house — kimonos, robes and silk camisoles for tropical lounging. Same Đồng Khởi door as the resort-wear boutique. Daily 8:30–21:30.",fib:["cotton","silk"]},
{n:"Catherine Denoual Maison",h:"",w:"https://www.catherinedenoual.com/",cat:"sleep",city:"SGN",area:"D1 · Bến Nghé",tier:"luxury",st:"walk",a:"38 Lý Tự Trọng, Q.1",price:"linen 1.25–3.13M₫ · silk 1.95–5.73M₫",no:"Saigon linen house — stone-washed linen & silk pyjamas, kimonos, nightdresses; the city's best sleep fabrics. +84 28 3823 9394.",fib:["linen","silk"]},
{n:"Wacoal (Takashimaya)",h:"",w:"https://wacoal.com.vn/",cat:"sleep",city:"SGN",area:"D1 · Bến Nghé",tier:"luxury",st:"walk",a:"L2 Takashimaya, 65 Lê Lợi, Q.1",no:"Japanese fitting service — nightdresses + sleep sets alongside the lingerie core; 8 HCMC-area stores incl. 232 Hai Bà Trưng (Tân Định)."},
{n:"Tricia & Verona",h:"",w:"https://triciaandverona.com/",cat:"sleep",city:"SGN",area:"D1 · Đông Du",tier:"couture",st:"appt",a:"37 Đông Du, Q.1",no:"Family bespoke house opposite the Sheraton — made-to-measure silk/cotton PJ sets in your fabric; email sales@triciaandverona.com first.",fib:["silk","cotton"]},
{n:"Thomas Nguyen Tailor",h:"",w:"https://thomasnguyentailor.com/",cat:"sleep",city:"SGN",area:"Gò Vấp",tier:"couture",st:"appt",a:"445/2/2G Quang Trung, P.10, Gò Vấp",no:"Bespoke house since 2012 — treat pyjamas as a custom shirt-and-trouser commission in your fabric; alterations up to 3 years.",flag:1},

/* — Hanoi — */
{n:"Mira Emb",h:"mira.emb",cat:"women",city:"HAN",area:"Hanoi",tier:"premium",st:"walk",a:"135 Lê Duẩn",no:"Handmade embroidery."},
{n:"Gèrme",h:"germe.vn",cat:"women",city:"HAN",area:"Hanoi · 3 stores",tier:"premium",st:"walk",a:"188 Bà Triệu + 237 Cầu Giấy + 73 Tràng Thi",no:"9:00–22:00; freeship nationwide."},
{n:"CE CE",h:"ce.ce_studio",cat:"women",city:"HAN",area:"Hanoi · Đống Đa",tier:"premium",st:"walk",a:"115B6 (verify) Phạm Ngọc Thạch",no:"“More value than you expect.” Made in VN."},
{n:"Happy Hahaha Studio",h:"happyhahahastudio",cat:"women",city:"HAN",area:"Hanoi · Hoàn Kiếm",tier:"mid",st:"walk",a:"14B1 Lý Nam Đế",no:"Own designs + China/Korea in-stock mix."},
{n:"Striped T",h:"striped.t",cat:"women",city:"HAN",area:"Hanoi",tier:"mid",st:"walk",a:"105B Thanh Bình, Hà Nội",no:"Worldwide shipping; confirm district."},
{n:"Josephine (Hanoi)",h:"josephineofficial.vn",cat:"women",city:"HAN",area:"Hanoi · Hai Bà Trưng",tier:"premium",st:"walk",a:"275 Phố Huế",no:"Hanoi branch of the D1 label."},
{n:"Lan Hương Fashion House",h:"",cat:"tailor",city:"HAN",area:"Hanoi · Tây Hồ",tier:"couture",st:"appt",a:"18 Âu Cơ",no:"Áo dài haute couture in a 1,300 m² colonial villa; state-event pieces."},
{n:"Tan My Design",h:"",cat:"tailor",city:"HAN",area:"Hanoi · Hoàn Kiếm",tier:"premium",st:"walk",a:"61 Hàng Gai",no:"4-generation hand embroidery + silk tailoring since 1969.",fib:["silk"]},
{n:"Kilomet109",h:"kilomet109",cat:"luxury",city:"HAN",area:"Hanoi · appt",tier:"couture",st:"appt",a:"Studio, appointment only",no:"Seed-to-garment eco couture; VN's most internationally cited slow-fashion designer.",fib:["hemp","cotton"]},
{n:"CHATS by C.DAM",h:"chatsbycdam",cat:"luxury",city:"HAN",area:"Hanoi · Hai Bà Trưng",tier:"couture",st:"walk",a:"47 Mai Hắc Đế",no:"Architectural couture; dressed Esther Yu at Cannes 2026."},
{n:"Hoàng Minh Hà",h:"hoangminhha__",cat:"luxury",city:"HAN",area:"Hanoi · appt",tier:"couture",st:"appt",a:"Atelier by appointment",no:"Haute-couture incl. áo dài; opened Aquafina VIFW FW2022."},

/* — Hà Linh Thu / Trần Hùng straddle Hanoi + a Saigon door — */
{n:"Hà Linh Thu",h:"halinhthu",cat:"luxury",city:"SGN",area:"Bình Thạnh + Hanoi",tier:"couture",st:"appt",a:"59 Ngô Tất Tố, Bình Thạnh (HCMC) + Hanoi atelier",no:"Hand-crafted silk “wearable art”; one of Hanoi's longest-running couture houses.",fib:["silk"]},
{n:"Trần Hùng",h:"tranhungofficial",cat:"luxury",city:"SGN",area:"Thủ Đức + Hanoi",tier:"luxury",st:"walk",a:"383 Nguyễn Duy Trinh, Thủ Đức (HCMC) + Hanoi",no:"First Vietnamese London Fashion Week member; 12+ LFW collections."},
{n:"Phan Đăng Hoàng",h:"_phandanghoang_",cat:"luxury",city:"SGN",area:"D1 · Milan (verify)",tier:"couture",st:"appt",a:"36 Đặng Thị Nhu, D1 — single-source",no:"First Vietnamese brand on the Milan Fashion Week runway; Forbes 30U30."},

/* — Other Vietnam — */
{n:"Dimo",h:"dimo.foru",cat:"women",city:"VN",area:"Đà Nẵng",tier:"mid",st:"online",a:"Home atelier, online",no:"“Tiệm may nhà làm.”"},
{n:"Shu Shi",h:"shushi_clothing",cat:"women",city:"VN",area:"Buôn Ma Thuột",tier:"mid",st:"walk",a:"60 Nguyễn Thị Minh Khai",no:"Linen; IG ~35% below Shopee.",fib:["linen"]},

/* — Markets & pop-ups — */
{n:"Rue Miche L'Édition",h:"ruemiche",cat:"market",city:"SGN",area:"D1 · Đồng Khởi",tier:"none",st:"walk",a:"Union Square B3, 171 Đồng Khởi",no:"SE Asia's largest multi-brand local-fashion store: 4,728 m², 120+ VN brands + rotating pop-ups. 10:00–21:30."},
{n:"The New Playground",h:"thenewplayground",cat:"market",city:"SGN",area:"D1 · Bến Nghé",tier:"none",st:"walk",a:"26 Lý Tự Trọng",no:"Underground concept mall — 50+ local streetwear brands; seasonal events."},
{n:"Hello Weekend Market",h:"helloweekendmarket",cat:"market",city:"SGN",area:"D1 · roams",tier:"none",st:"popup",a:"Usually Hoa Lư Stadium, 2–4 Đinh Tiên Hoàng",no:"HCMC's biggest youth fashion fair since 2013; check IG for the weekend venue."},
{n:"The Box Market",h:"",cat:"market",city:"SGN",area:"D1",tier:"none",st:"popup",a:"125 Hai Bà Trưng + Lê Lai",no:"Curated indie: young fashion, handmade accessories, vintage.",fib:["circular"]},
{n:"Saigon Flea Market",h:"",cat:"market",city:"SGN",area:"D7 · Phú Mỹ Hưng",tier:"none",st:"popup",a:"Boomerang Bistro",no:"1st & 3rd Sunday; handmade + vintage pioneer market.",fib:["circular"]},
{n:"Saigon Vintage Market",h:"",cat:"market",city:"SGN",area:"Roams",tier:"none",st:"popup",a:"Recent: Bloq Saigon",no:"Curated vintage/preloved — a stylist favourite.",fib:["circular"]},
{n:"Saigon Urban Flea",h:"",cat:"market",city:"SGN",area:"Thảo Điền",tier:"none",st:"popup",a:"Saigon Outcast, 188/1 Nguyễn Văn Hưởng",no:"Vintage/secondhand + artisan craft + workshops.",fib:["circular"]},
{n:"Thiso Mall pop-ups",h:"",cat:"market",city:"SGN",area:"Thủ Thiêm",tier:"none",st:"popup",a:"10 Mai Chí Thọ",no:"Rotating short brand pop-ups; check the current lineup."},

/* — Established Saigon walk-ins (June-verified) — */
{n:"OnOnMM ®",h:"ononmm.monde",cat:"women",city:"SGN",area:"D1 · Bến Thành",tier:"premium",st:"walk",a:"1C Lê Thị Riêng",no:"Established minimalist label. 9:00–21:30."},
{n:"Cocosin",h:"cocosin.official",cat:"women",city:"SGN",area:"D3 · P.5",tier:"premium",st:"walk",a:"365 Võ Văn Tần",no:"Long-running favourite; polished feminine RTW. 9:00–21:30."},
{n:"Libé",h:"libeworkshop",cat:"women",city:"SGN",area:"D1",tier:"premium",st:"walk",a:"52 Nguyễn Trãi + 26 Lý Tự Trọng",no:"Libé Workshop — elevated everyday staples."},
{n:"Wephobia",h:"wephobiastudio",cat:"women",city:"SGN",area:"D1 · Bến Thành",tier:"premium",st:"walk",a:"98 Lý Tự Trọng",no:"Cool-girl contemporary RTW. 9:00–21:30."},
{n:"Nosbyn",h:"nosbyn",cat:"women",city:"SGN",area:"D1 · Bến Thành",tier:"premium",st:"walk",a:"9 Phan Chu Trinh + Thảo Điền",no:"Minimalist wardrobe staples; also the Thảo Điền studio."},
{n:"Daphale Studios",h:"daphalestudios",cat:"women",city:"SGN",area:"D1 / D3",tier:"premium",st:"walk",a:"272C Pasteur + 22 Đặng Thị Như + Vincom",no:"Contemporary designer RTW; three points of sale."},
{n:"Whenever Atelier",h:"whenever.atelier",cat:"women",city:"SGN",area:"D3",tier:"premium",st:"walk",a:"141/8 Bàn Cờ + Vincom 26 Lý Tự Trọng",no:"Tailoring-led womenswear. 10:00–21:00."},
{n:"Kathy Atelier",h:"kathy.atelier.vn",cat:"women",city:"SGN",area:"D3 · P.14",tier:"premium",st:"walk",a:"6 Trần Quang Diệu",no:"Anchors the Trần Quang Diệu design strip. 10:00–21:00."},
{n:"Laneci",h:"laneci.stu",cat:"women",city:"SGN",area:"D3 · P.14",tier:"premium",st:"walk",a:"27 Trần Quang Diệu",no:"Refined feminine RTW on the TQD strip. 10:00–22:00."},
{n:"Sò Vintage",h:"sovintage_house",cat:"women",city:"SGN",area:"D3 · Võ Thị Sáu",tier:"mid",st:"walk",a:"200 Nguyễn Thị Minh Khai, Phường Võ Thị Sáu, Quận 3",no:"Curated vintage.",fib:["circular"]},
{n:"Anna Clothes",h:"annaclothing.vn",cat:"women",city:"SGN",area:"D3 / D1 / Gò Vấp",tier:"mid",st:"walk",a:"292/26 CMT8 + 73 Nguyễn Cư Trinh + Gò Vấp",no:"Cute, affordable RTW; several branches."},
{n:"Levents",h:"leventsbrand",cat:"women",city:"SGN",area:"D1 / Q10",tier:"mid",st:"walk",a:"325 Hoàng Sa + 139E Nguyễn Trãi + 842 Sư Vạn Hạnh",no:"Cult local streetwear. 10:00–21:30."},
{n:"Hangkao Closet",h:"hangkao_closet",cat:"women",city:"SGN",area:"D3 · P.14",tier:"mid",st:"walk",a:"448/9 Lê Văn Sỹ",no:"Trend-led local closet."},
{n:"Veos",h:"veosbykhanh",cat:"women",city:"SGN",area:"D1",tier:"mid",st:"walk",a:"279 Nguyễn Trãi",no:"Contemporary RTW."},
{n:"Thao Bibi",h:"thao_bibii",cat:"women",city:"SGN",area:"Q5 · Chợ Quán",tier:"mid",st:"walk",a:"128 Nguyễn Trãi",no:"Popular local womenswear."},
{n:"LaLune",h:"_lalune_official_",cat:"women",city:"SGN",area:"Online",tier:"premium",st:"online",a:"laluneofficial.com — DM",no:"Online gallery; elevated feminine RTW."},
{n:"Mael Femme",h:"mael.femme",cat:"women",city:"SGN",area:"Online / showroom",tier:"premium",st:"online",a:"DM for showroom/appointment",no:"Sells online; registered at Saigon Centre."},
{n:"Bupbes",h:"",w:"https://bupbes.com/",cat:"women",city:"SGN",area:"Online",tier:"mid",st:"online",a:"bupbes.com",no:"Online boutique."},

/* — HCMC online-only — */
{n:"Kae",h:"kae_fficial",cat:"women",city:"SGN",area:"Online",tier:"mid",st:"online",a:"DM · kae.fficial@gmail.com",no:"Worldwide shipping."},
{n:"Aisytum",h:"aisytum",cat:"women",city:"SGN",area:"Online",tier:"mid",st:"online",a:"beacons.ai/by.aisytum",no:"Thiết kế; IG cheaper than Shopee."},
{n:"Miah Noir",h:"miah.noir",cat:"women",city:"SGN",area:"Online",tier:"mid",st:"online",a:"DM, pre-order",no:"No COD; worldwide."},
{n:"Is Flourish",h:"is.flourish",cat:"women",city:"SGN",area:"Online",tier:"mid",st:"online",a:"DM to order",no:"Handmade in Vietnam."},
{n:"Lussera",h:"lussera.vita",cat:"women",city:"SGN",area:"Online",tier:"mid",st:"online",a:"DM",no:"Hometown HCMC; worldwide."},
{n:"Szombies",h:"szombies.official",cat:"women",city:"SGN",area:"Online",tier:"mid",st:"online",a:"shopee.vn/szombies",no:"Worldwide shipping."},
{n:"Wabitales",h:"wabitales",cat:"women",city:"SGN",area:"Online",tier:"mid",st:"online",a:"shopee.vn/wabitales",no:"Online clothing shop."},
{n:"Vanila Gals",h:"vanila.gals",cat:"women",city:"SGN",area:"Online",tier:"mid",st:"online",a:"DM / FB",no:"Based in HCMC; worldwide."},
{n:"Amory",h:"amory.storevn",cat:"women",city:"SGN",area:"Online",tier:"mid",st:"online",a:"Shopee",no:"Embracing beauty, anywhere."},
{n:"Xinh Hà",h:"xinhhaofficial",cat:"women",city:"SGN",area:"Online",tier:"mid",st:"online",a:"WhatsApp +84 964 989898",no:"RTW design; PayPal accepted."},
{n:"Sensore",h:"sensore.studio",cat:"women",city:"SGN",area:"Online",tier:"mid",st:"online",a:"DM · Zalo 0937427006",no:"Saigon; 11:00–21:00."},
{n:"Lovelyn",h:"lovelyn.global",cat:"women",city:"SGN",area:"Online",tier:"mid",st:"online",a:"lovelyn.co",no:"Worldwide shipping."},
{n:"Punch",h:"punch.vn",cat:"women",city:"SGN",area:"Online",tier:"mid",st:"online",a:"shopee.vn/punchvn",no:"Online in Saigon; worldwide."},

/* — Vietnam-based, city not stated (online) — */
{n:"Perpearl",h:"perpearlofficial",cat:"women",city:"VN",area:"Online · VN",tier:"mid",st:"online",a:"perpearl.com",no:"Girls are Pearls."},
{n:"Katherine Studio",h:"katherine_studios",cat:"women",city:"VN",area:"Online · VN",tier:"mid",st:"online",a:"Shopee · linkbio",no:"Made in VN; ships worldwide."},
{n:"Jujubae",h:"jujubae.official",cat:"women",city:"VN",area:"Online · VN",tier:"mid",st:"online",a:"shopee.vn/jujubae.official",no:"Since 2021; coquette dresses."},
{n:"Lụa Là by Diễm",h:"lualabydiem",cat:"women",city:"VN",area:"Online · VN",tier:"mid",st:"online",a:"vn.shp.ee/APdvJoh",no:"Silk.",fib:["silk"]},
{n:"OCÉARA",h:"oceara.official",cat:"women",city:"VN",area:"Online · VN",tier:"mid",st:"online",a:"Shopee",no:"Vietnam-based online shop."},
{n:"Some Official",h:"someofficial.vn",cat:"women",city:"VN",area:"Online · VN",tier:"premium",st:"online",a:"beacons.ai/someofficial",no:"Minimal chic; no COD."},
{n:"Brown VN",h:"brown.vn",cat:"women",city:"VN",area:"Online · VN",tier:"mid",st:"online",a:"brownvn.com",no:"Online exclusive, no Shopee."},
{n:"Matemade",h:"matemade.official",cat:"women",city:"VN",area:"Online · VN",tier:"mid",st:"online",a:"shopee.vn/matemade.vn",no:"Have a taste."},
{n:"Jennie Choo",h:"jenniechoo.official",cat:"women",city:"VN",area:"Online · VN",tier:"mid",st:"online",a:"jenniechoo.vn",no:"Princess-y dresses."},
{n:"By Cotno",h:"bycotno",cat:"women",city:"VN",area:"Online · VN",tier:"mid",st:"online",a:"DM · cotno.loveu@gmail.com",no:"Worldwide shipping."},
{n:"Velvet Venom",h:"velvetvenomofficial",cat:"women",city:"VN",area:"Online · VN",tier:"premium",st:"online",a:"velvetvenom.co",no:"Slow fashion, handcrafted."},
{n:"Rid Kid Closet",h:"ridkidcloset",cat:"women",city:"VN",area:"Online · VN",tier:"mid",st:"online",a:"DM",no:"Handmade custom couture."},
{n:"Vintage Angel Tailor",h:"vintage.angel.tailor",cat:"women",city:"VN",area:"Online · VN",tier:"mid",st:"online",a:"DM",no:"Made-to-measure, handmade limited."},
{n:"Feiin Atelier",h:"feiin.atelier",cat:"women",city:"VN",area:"Online · VN",tier:"mid",st:"online",a:"shopee.vn/feiin_atelier",no:"Lingerie sister label too."},
{n:"Dune De Label",h:"dune.delabel",cat:"women",city:"VN",area:"Online · VN",tier:"premium",st:"online",a:"Shopee VN/TH/SG",no:"Bikini, resort & RTW."},
{n:"Aoi Zone",h:"aoi_zone",cat:"women",city:"VN",area:"Online · VN",tier:"mid",st:"online",a:"Shopee",no:"Dolls of apocalypse."},
{n:"Her Day Off",h:"her.dayoff",cat:"women",city:"VN",area:"Online · VN",tier:"mid",st:"online",a:"Stocked at @nayykiaa.empor",no:"Stockist address unconfirmed."},
{n:"Sonancy Mood",h:"sonancy.mood",cat:"women",city:"VN",area:"Online · VN",tier:"mid",st:"online",a:"DM",no:"In the mood for summer."},
{n:"Aeva Atelier",h:"aevaatelier",cat:"women",city:"VN",area:"Online · VN",tier:"mid",st:"online",a:"aevaatelier.com",no:"Check site for details."},
{n:"Weekend Hub",h:"weekendhub_official",cat:"women",city:"VN",area:"Online · VN",tier:"mid",st:"online",a:"DM",no:"Novel aesthetics for girls."},
{n:"Bubble",h:"bubble.slayyy",cat:"women",city:"VN",area:"Online · VN",tier:"mid",st:"online",a:"bubbleslay.vn",no:"In-house designs."},
{n:"Aguja Studio",h:"aguja.studio",cat:"women",city:"VN",area:"Online · VN",tier:"mid",st:"online",a:"shopee.vn/aguja.studio",no:"Online studio."},
{n:"Swessy",h:"swessy.ss",cat:"women",city:"VN",area:"Online · VN",tier:"mid",st:"online",a:"DM",no:"Born sweet; designed in VN."},
{n:"The Nicolette House",h:"thenicolettehouse",cat:"women",city:"VN",area:"Online · VN",tier:"mid",st:"online",a:"thenicolettehouse.com",no:"Est. 2021; online only."},
{n:"Aimee",h:"aimeee.sg",cat:"women",city:"VN",area:"Online · VN",tier:"mid",st:"online",a:"shopee.vn/aimee.sg",no:"Online only."},
{n:"Laling",h:"laling.official",cat:"women",city:"VN",area:"Online · VN",tier:"mid",st:"online",a:"lalingofficial.com",no:"Your beauty, our inspiration."},
{n:"Rosie",h:"rosieofficial.vn",cat:"women",city:"VN",area:"Online · VN",tier:"mid",st:"online",a:"DM",no:"Worldwide delivery."},
{n:"Morris",h:"morris.officiall",cat:"women",city:"VN",area:"Online · VN",tier:"mid",st:"online",a:"FB Morris Official",no:"Separate brand from Mooris (D3 store)."},
{n:"Keira Tong",h:"keiratong.official",cat:"women",city:"VN",area:"Online · VN",tier:"premium",st:"online",a:"keiratong.com",no:"Designer label."},
{n:"OAK — Wear of a Kind",h:"wear_ofakind",cat:"women",city:"VN",area:"Online · VN",tier:"mid",st:"online",a:"msha.ke/wear_oak",no:"Curated rare VN + Indonesian pieces."},
{n:"Kaiiros",h:"kaiiros.official",cat:"women",city:"VN",area:"Online · VN",tier:"premium",st:"online",a:"Shopee",no:"Australian/Vietnamese label."},
{n:"Guvie",h:"guvie.official",cat:"women",city:"VN",area:"Online · VN",tier:"mid",st:"online",a:"Shopee",no:"Design fashion."},
{n:"Sundei",h:"sundei.studio",cat:"women",city:"VN",area:"Online · VN",tier:"mid",st:"online",a:"Shopee",no:"Online studio."},
{n:"Sister Sister by Min",h:"sistersisterbymin",cat:"women",city:"VN",area:"Online · VN",tier:"mid",st:"online",a:"shopee.vn/sistersisterbymin",no:"Basic, elegant looks."},
{n:"Thrifty Chuối",h:"thrifty.chuoi",cat:"women",city:"VN",area:"Online · VN",tier:"mid",st:"online",a:"DM · PayPal/Wise",no:"Thrift; worldwide from $15."},
{n:"Velia Co",h:"velia.co",cat:"access",sub:"Bags",city:"VN",area:"Online · VN",tier:"mid",st:"online",a:"FB",no:"Name-engraved bags."},

/* — Hanoi online — */
{n:"Mood Emode",h:"mood.emode",cat:"women",city:"HAN",area:"Hanoi · online",tier:"premium",st:"online",a:"DM · FB moodemode2019",no:"Tailor house / atelier."},
{n:"Kistiny",h:"kistiny.ig",cat:"women",city:"HAN",area:"Hanoi · online",tier:"mid",st:"online",a:"DM · 0888040309",no:"Ships 10–14 days."},
{n:"By Fairy",h:"byfairy.vn",cat:"women",city:"HAN",area:"Hanoi · online",tier:"mid",st:"online",a:"shopee.vn/byfair.vn",no:"Online store."},
{n:"Poppy Babi",h:"poppybabi.couture",cat:"tailor",city:"HAN",area:"Hanoi · online",tier:"premium",st:"online",a:"DM / FB",no:"Silk made-to-measure tailor.",fib:["silk"]},

/* — Remaining athleisure — */
{n:"I.Sport",h:"",cat:"active",city:"SGN",area:"Bình Thạnh",tier:"premium",st:"walk",a:"549/43 Xô Viết Nghệ Tĩnh",no:"Gray-import boutique (Alo / Lorna Jane / Lululemon) — verify each piece.",flag:1},
{n:"Coolmate",h:"",cat:"active",city:"HAN",area:"Hanoi · Đống Đa",tier:"mid",st:"walk",a:"B2, Hanoi Centre, 175 Nguyễn Thái Học",no:"Online-first D2C giant — no HCMC retail store (Thủ Đức offices/warehouse only); women's line since Mar 2025. UPF 50+ UV Protection collection, Intertek-tested."},
{n:"Hibi Sports",h:"",cat:"active",city:"SGN",area:"Online",tier:"mid",st:"online",a:"hibisports.com",no:"Online-first women's yoga/gym wear."},
{n:"Kydra",h:"",cat:"active",city:"INTL",area:"Singapore",tier:"premium",st:"online",a:"kydra.co",no:"Ships to VN; no VN stockist."},

/* — Vietnamese-owned athleisure (aeyo & coastal/studio kin) — */
{n:"aeyo",h:"aeyo.fit",cat:"active",city:"SGN",area:"Online",tier:"premium",st:"online",a:"shopee.vn/aeyo.fit · IG",vibe:"studio",no:"Studio-to-street, made in VN; flattering, shoots well. @aeyo.fit is the active account (@aeyogirlsclub is login-walled)."},
{n:"Augety",h:"augety.st",cat:"active",city:"SGN",area:"Online",tier:"mid",st:"online",a:"augetystudio.com · Shopee",vibe:"studio",no:"HCMC-based feminine gym-to-café sets; figure-flattering."},
{n:"ONWAYS",h:"onway.sportswear",cat:"active",city:"SGN",area:"Thủ Đức · An Khánh",tier:"mid",st:"walk",a:"62 Hoàng Thế Thiện",vibe:"studio",no:"Coffee-yarn (S.Café) is recycled PET — polyester, not a natural fibre. Light-performance basics."},
{n:"Alva Activewear",h:"",cat:"active",city:"SGN",area:"D6",tier:"mid",st:"walk",a:"96 Bà Hom (Chi Sport)",vibe:"studio",no:"Budget export-surplus (VNXK) yoga/crop sets; flattering. IG unconfirmed."},

/* — California / coastal athleisure canon (overseas; ships-to-VN noted) — */
{n:"Set Active",h:"",cat:"active",city:"INTL",area:"California, USA",tier:"premium",st:"online",a:"setactive.co — ships to VN",vibe:"coastal",no:"Elevated matching sets in seasonal colour drops; sculpting 'it-girl'. Ships to Vietnam."},
{n:"Splits59",h:"",cat:"active",city:"INTL",area:"California, USA",tier:"premium",st:"online",a:"splits59.com — ships to VN",vibe:"coastal",no:"Retro-sporty '70s track / '80s aerobics; polished sporty-refined. Ships to Vietnam."},
{n:"Aviator Nation",h:"",cat:"active",city:"INTL",area:"Venice, California",tier:"premium",st:"online",a:"aviatornation.com — likely ships VN",vibe:"coastal",no:"1970s CA surf/vintage; signature stitched stripes on brushed fleece."},

/* — Asian fashion outside Vietnam — */
{n:"Mimilys",h:"mimilysshop",cat:"women",city:"INTL",area:"Thailand",tier:"mid",st:"online",a:"Worldwide; Wise/Remitly",no:"Vintage secondhand.",fib:["circular"]},
{n:"Jula",h:"julalinekw",cat:"women",city:"INTL",area:"Kuwait",tier:"premium",st:"walk",a:"The Avenues Phase 3 + Shuwaikh",no:"Occasion dresses, designed in Kuwait."},
/* — Natural fibre, certified cotton & circular · added July 2026 —
   Clients are increasingly polyester-averse. Every house below states its own fibre;
   `fib` records what THEY say, not what a listicle says. `flag:1` = the address or the
   fibre claim rests on a single source — phone before you send a client. — */
{n:"The 31",h:"the31_vn",w:"https://the31.vn/",cat:"women",city:"SGN",area:"Thảo Điền",tier:"premium",st:"walk",a:"16 Quốc Hương",no:"Plant-based only: linen from France & Holland, organic cotton from India. Men & women.",fib:["linen","cotton"]},
{n:"Ginkgo T-shirts",h:"ginkgotshirts",w:"https://ginkgotshirts.com/",cat:"women",city:"SGN",area:"D1 · Bến Nghé",tier:"mid",st:"walk",a:"10 Lê Lợi (+ 3 more D1 doors)",no:"GOTS organic-cotton tees, polos & shirts — some styles blend elastane. Men & women.",fib:["cotton"]},
{n:"Cuddle",h:"cuddle.linenclothing",w:"https://cuddle.vn/",cat:"women",city:"SGN",area:"Thảo Điền",tier:"premium",st:"walk",a:"7 Đường số 1",no:"100% pure linen since 2017; linen bedding too. Menswear line = emdash, same door.",fib:["linen"]},
{n:"emdash",h:"emdash_saigon",w:"https://cuddle.vn/collections/emdash-linen-for-men",cat:"men",city:"SGN",area:"Thảo Điền",tier:"premium",st:"walk",a:"7 Đường số 1",no:"Cuddle's menswear line (2023) — linen shirts, trousers, sets. Same Thảo Điền door.",fib:["linen"]},
{n:"TimTay",h:"timtayofficial",w:"https://timtay.me/",cat:"women",city:"SGN",area:"D7 · Tân Hưng",tier:"premium",st:"walk",a:"20/9 Nguyễn Bính (+ Phú Mỹ Hưng concept store)",no:"Zero-waste cutting since 2014 — linen, cotton & mulberry silk. 10:00–19:00 daily.",fib:["linen","cotton","silk"]},
{n:"Rustea",h:"rustea.vn",w:"https://rustea.vn/",cat:"women",city:"SGN",area:"Thủ Đức · Thảo Điền",tier:"mid",st:"walk",a:"23A Đường số 54, Thảo Điền",no:"Unisex linen, cotton & silk since 2017. A second Thảo Điền door is listed — call 0899 899 767.",fib:["linen","cotton","silk"],flag:1},
{n:"Mêman",h:"meman.saigon",cat:"men",city:"SGN",area:"D1 · Bến Nghé",tier:"premium",st:"walk",a:"26B–C Lê Lợi",no:"Minimalist menswear & modern áo dài in Japanese linen. 11:00–20:00.",fib:["linen"]},
{n:"Moriko Saigon",h:"linenbymoriko",w:"https://morikosaigon.vn/",cat:"women",city:"SGN",area:"Phú Nhuận",tier:"premium",st:"walk",a:"158/37 Trần Huy Liệu",no:"Linen & hand-embroidery house since 2018; linen áo dài and silk. 9:00–20:00.",fib:["linen","silk"]},
{n:"Leinné",h:"leinne.brand",w:"https://leinne.com/",cat:"access",sub:"Hats & bags",city:"SGN",area:"D1 · Cầu Ông Lãnh",tier:"premium",st:"appt",a:"135/43 Trần Hưng Đạo",no:"Madagascar raffia hats & bags, organic silk; private showroom — book on Zalo first.",fib:["silk","linen"]},
{n:"Xéo Xọ",h:"xeoxo",w:"https://xeoxo.com/",cat:"women",city:"SGN",area:"D1 · Bến Nghé",tier:"premium",st:"walk",a:"43 Đặng Thị Nhu",no:"Hanoi-born silk label with a D1 door; fibre % not published — ask. 10:00–21:00.",fib:["silk"],flag:1},
{n:"Canary Linen",h:"canary.linen",w:"https://canarylinen.vn/",cat:"women",city:"SGN",area:"D1 · Bến Thành",tier:"mid",st:"walk",a:"89B Cách Mạng Tháng 8",no:"Linen-look daily wear; 100% cotton tees confirmed, linen % not published — ask.",fib:["cotton"],flag:1},
{n:"Bảo Lộc Silk",cat:"tailor",city:"SGN",area:"D1 · Đa Kao",tier:"premium",st:"walk",a:"12 Mạc Đĩnh Chi",no:"100% silk by the metre from the Bảo Lộc silk capital — bring it to a tailor.",fib:["silk"],flag:1},
{n:"Toàn Thịnh Silk",w:"https://toanthinhsilk.com/",cat:"tailor",city:"SGN",area:"D1 · Bến Thành",tier:"mid",st:"walk",a:"258 Lê Thánh Tôn",no:"Silk by the metre, 9:00–21:00. They also sell satin — check it is silk satin, not poly.",fib:["silk"],flag:1},
{n:"Mui The Label",h:"muithelabel",w:"https://muithelabel.com/",cat:"women",city:"VN",area:"Hội An",tier:"mid",st:"walk",a:"15B Lê Lợi, Hội An",no:"Hội An boho boutique since 2016 — hand-made small batches, linen. 9:30–22:30.",fib:["linen"],flag:1},
{n:"Saigon Concepts",h:"saigon_concepts",w:"https://shop.saigonconcepts.com/",cat:"sleep",city:"SGN",area:"Bình Thạnh · by appointment",tier:"premium",st:"online",a:"Online; studio by appointment",no:"Deadstock 100% cotton, linen & TENCEL pyjamas cut in a Saigon studio. No published address.",fib:["cotton","linen","tencel","circular"]},
{n:"Lơ Silk",h:"losilkvietnam",w:"https://www.losilkvietnam.com/",cat:"sleep",city:"SGN",area:"D1 · Bến Nghé",tier:"luxury",st:"walk",a:"87B Pasteur",no:"100% Bảo Lộc silk, plant-dyed, OEKO-TEX. The slips are the lounge pieces. 10:00–20:00.",fib:["silk"]},
{n:"BYFAS",w:"https://byfas.com/",cat:"sleep",city:"SGN",area:"D1 · Bến Nghé",tier:"premium",st:"appt",a:"40 Ngô Đức Kế",no:"Bespoke pyjamas in natural silk, linen or poplin — from ~$250/set. ☎ 090 583 6118.",fib:["silk","linen"]},
{n:"Bon Bon Underwear",w:"https://bonbonunderwear.com.vn/",cat:"sleep",city:"SGN",area:"D1 · Tân Định",tier:"mid",st:"walk",a:"432 Hai Bà Trưng",no:"Lingerie chain with a real cotton line; fibre % not published — ask. On the HBT strip.",fib:["cotton"],flag:1},
{n:"CHOI — Organic Cotton",w:"https://organiccotton.vn/",cat:"sleep",city:"SGN",area:"Tân Bình · online",tier:"mid",st:"online",a:"Online only — no shop",no:"IVN-certified organic-cotton briefs, bras & basics. They state plainly: online only.",fib:["cotton"]},
{n:"Voga Underwear",w:"https://voga.com.vn/",cat:"sleep",city:"SGN",area:"Thủ Đức · online",tier:"mid",st:"online",a:"Online (Shopee Mall + own site)",no:"Men's briefs, vests & tanks in 90% Lenzing Modal. Modal is regenerated cellulose, not cotton.",fib:["tencel"],flag:1},
{n:"Decathlon (Kimjaly)",w:"https://www.decathlon.vn/",cat:"active",city:"SGN",area:"Thủ Đức · Thảo Điền",tier:"mid",st:"walk",a:"L1, Vincom Mega Mall Thảo Điền, 161 Xa Lộ Hà Nội",vibe:"studio",no:"The only walk-in organic-cotton yoga bottoms in the city. Every local activewear label is polyester.",fib:["cotton"]},
{n:"In The Mood Saigon",h:"inthemoodsaigonstore",cat:"market",city:"SGN",area:"Thảo Điền",tier:"none",st:"walk",a:"32 Trần Ngọc Diện",no:"Multi-brand concept store — stocks Nora Linen and local linen labels. 10:00–18:00.",fib:["linen"],flag:1},
{n:"Chợ Bà Chiểu",cat:"market",city:"SGN",area:"Bình Thạnh · P.1",tier:"none",st:"walk",a:"Bùi Hữu Nghĩa & Diên Hồng, P.1",no:"Old-Saigon market; đồ si (secondhand) racks, fabric & shoes in the west wing. Kiosks shut ~19:00.",fib:["circular"]}
];
