/* Seraphic Styler — link-page (links) translations.
   Merges the link-page-only strings into window.SS_TRANSLATIONS so the
   language toggle translates the whole page. Kept separate from the big
   translations.js to stay easy to edit. English is the source (in the HTML),
   so no "en" block is needed; any language missing a key falls back to English.
   Load order: translations.js -> links-i18n.js -> i18n.js. */
(function () {
  'use strict';
  var T = window.SS_TRANSLATIONS = window.SS_TRANSLATIONS || {};
  var add = {
    vi: {
      'lp.trust': 'TP. Hồ Chí Minh · Phản hồi trong 1–2 ngày làm việc',
      'lp.estlink': 'hoặc nhận báo giá nhanh →',
      'lp.proof1': 'Giao toàn cầu',
      'lp.proof2': 'Kiểm tận nơi',
      'lp.proof3': 'Tư vấn form thật lòng',
      'lp.order_t': 'Đặt bất kỳ thương hiệu Việt nào',
      'lp.order_s': 'Kể cả món chưa đăng — gửi mình wishlist của bạn',
      'lp.dir_t': 'Danh mục Thời trang Sài Gòn',
      'lp.dir_s': '239 thương hiệu đã xác minh, sắp xếp theo quận',
      'lp.fg_t': 'Cẩm nang mua sắm Sài Gòn',
      'lp.fg_s': 'Di chuyển, ăn mặc hợp thời tiết nóng, và lịch trình từ 1 đến 30 ngày',
      'lp.houses_t': 'Khám phá các nhà mốt',
      'lp.houses_s': 'Chạm vào biểu tượng bất kỳ để mở trong danh mục',
      'lp.est_t': 'Nhận báo giá nhanh',
      'lp.est_s': 'Ước tính trong vài giây, rồi nhắn tin hoặc email cho mình',
      'lp.ig_s': 'Hàng mới & video phối đồ mỗi ngày · @seraphicstyler',
      'lp.tt_s': 'Clip phối đồ & mở hàng · @seraphicstyler',
      'lp.look_s': 'Nguồn hàng & phối đồ gần đây',
      'lp.email_t': 'Email',
      'lp.site_t': 'Xem trang đầy đủ',
      'lp.site_s': 'Dịch vụ, bảng giá & chính sách',
      'lp.foot': 'Đặt bất kỳ thương hiệu Việt nào — kể cả những món chưa đăng.<br>Giá rõ ràng, tư vấn form thật lòng, và giao hàng toàn cầu từ Sài Gòn.',
      'qe.eyebrow': 'Ước tính sơ bộ',
      'qe.title': 'Báo giá nhanh',
      'qe.sub': 'Ước tính trong vài giây. Không thanh toán — báo giá cuối được xác nhận khi bạn nhắn cho mình.',
      'qe.budget': 'Ngân sách món đồ (USD)',
      'qe.shipto': 'Giao đến',
      'qe.bulky': 'Cồng kềnh hoặc nhiều món (kiện nặng hơn)',
      'qe.rnote': 'ước tính trọn gói · tiền hàng + phí dịch vụ + vận chuyển',
      'qe.dm': 'Nhắn tin trên Instagram',
      'qe.email': 'Gửi báo giá này qua email',
      'qe.copied': '✓ Đã sao chép báo giá — chỉ cần dán vào tin nhắn.',
      'qe.full': 'Muốn công cụ ước tính chi tiết? Mở trang đầy đủ →',
      'a11y.title': 'Cài đặt',
      'theme.mono': 'Đơn sắc',
    },
    "zh": {"lp.dir_t":"西贡时尚名录","lp.dir_s":"239 家亲自核实的品牌，按区整理","lp.fg_t":"西贡购物实地指南","lp.fg_s":"怎么出行、暑热怎么穿，以及 1 到 30 天的行程","lp.houses_t":"浏览品牌","lp.houses_s":"点按任一标识，即可在名录中打开","lp.trust":"胡志明市 · 1–2 个工作日内回复","lp.estlink":"或快速获取预估 →","lp.proof1":"全球配送","lp.proof2":"亲自验货","lp.proof3":"诚实的版型建议","lp.order_t":"代购任何越南品牌","lp.order_s":"即使是未发布的单品——把你的心愿单发给我","lp.est_t":"快速获取预估","lp.est_s":"几秒钟得到大致报价，然后私信或邮件联系我","lp.ig_s":"每日好物与版型视频 · @seraphicstyler","lp.tt_s":"穿搭短片与开箱 · @seraphicstyler","lp.look_s":"近期代购与造型","lp.email_t":"邮件","lp.site_t":"浏览完整网站","lp.site_s":"服务、价格与政策","lp.foot":"代购任何越南品牌——包括未发布的单品。<br>清晰的价格、诚实的版型建议，从西贡发往世界各地。","qe.eyebrow":"大致预估","qe.title":"快速预估","qe.sub":"几秒钟得到大致报价。无需付款——最终报价将在你联系我时确认。","qe.budget":"单品预算（USD）","qe.shipto":"配送至","qe.bulky":"大件或多件商品（包裹较重）","qe.rnote":"总价预估 · 商品 + 服务费 + 运费","qe.dm":"在 Instagram 上私信","qe.email":"将此预估发邮件给我","qe.copied":"✓ 预估已复制——直接粘贴到私信里即可。","qe.full":"想要更详细的预估？打开完整网站 →","a11y.title":"设置","theme.mono":"单色"},
    "es": {"lp.dir_t":"El Directorio de Moda de Saigón","lp.dir_s":"239 casas verificadas, ordenadas por distrito","lp.fg_t":"La Guía de Campo para Comprar en Saigón","lp.fg_s":"Cómo moverte, cómo vestir con el calor e itinerarios de 1 a 30 días","lp.houses_t":"Explora las casas","lp.houses_s":"Toca cualquier marca para abrirla en el directorio","lp.trust":"Ciudad Ho Chi Minh · Respondo en 1–2 días hábiles","lp.estlink":"o consigue un presupuesto rápido →","lp.proof1":"Envíos a todo el mundo","lp.proof2":"Verificado en persona","lp.proof3":"Consejo honesto sobre el ajuste","lp.order_t":"Pide cualquier marca vietnamita","lp.order_s":"Incluso piezas que no he publicado: envíame tu lista de deseos","lp.est_t":"Consigue un presupuesto rápido","lp.est_s":"Una estimación en segundos y luego escríbeme por DM o correo","lp.ig_s":"Hallazgos diarios y vídeos de ajuste · @seraphicstyler","lp.tt_s":"Clips de estilismo y unboxings · @seraphicstyler","lp.look_s":"Compras y estilismos recientes","lp.email_t":"Correo","lp.site_t":"Visita el sitio completo","lp.site_s":"Servicios, precios y políticas","lp.foot":"Pide cualquier marca vietnamita, incluidas piezas que no he publicado.<br>Precios claros, consejo honesto sobre el ajuste y envíos a todo el mundo desde Saigón.","qe.eyebrow":"Estimación aproximada","qe.title":"Presupuesto rápido","qe.sub":"Una estimación en segundos. Sin pago: tu presupuesto final se confirma cuando me escribes.","qe.budget":"Presupuesto del artículo (USD)","qe.shipto":"Enviar a","qe.bulky":"Artículos voluminosos o varios (paquete más pesado)","qe.rnote":"estimación total · artículos + tarifa de servicio + envío","qe.dm":"Escríbeme por Instagram","qe.email":"Envíame este presupuesto por correo","qe.copied":"✓ Presupuesto copiado: solo pégalo en el DM.","qe.full":"¿Prefieres el estimador detallado? Abre el sitio completo →","a11y.title":"Ajustes","theme.mono":"Mono"},
    "ar": {"lp.dir_t":"دليل أزياء سايغون","lp.dir_s":"239 دارًا موثّقة شخصيًا، مرتّبة حسب الحي","lp.fg_t":"الدليل الميداني للتسوّق في سايغون","lp.fg_s":"كيف تتنقّلين، وكيف تلبسين في الحر، وبرامج من يوم إلى 30 يومًا","lp.houses_t":"تصفّحي دور الأزياء","lp.houses_s":"انقري على أي علامة لفتحها في الدليل","lp.trust":"مدينة هو تشي مِنه · أرد خلال يوم إلى يومَي عمل","lp.estlink":"أو احصل على تقدير سريع →","lp.proof1":"شحن إلى جميع أنحاء العالم","lp.proof2":"مُعايَنة شخصية موثوقة","lp.proof3":"نصيحة صادقة في المقاس","lp.order_t":"اطلبي أي ماركة فيتنامية","lp.order_s":"حتى القطع غير المنشورة — أرسلي لي قائمة رغباتك","lp.est_t":"احصلي على تقدير سريع","lp.est_s":"تقدير تقريبي في ثوانٍ، ثم راسليني عبر الرسائل الخاصة أو البريد","lp.ig_s":"اكتشافات يومية ومقاطع المقاسات · @seraphicstyler","lp.tt_s":"مقاطع تنسيق وفتح طرود · @seraphicstyler","lp.look_s":"أحدث المصادر والتنسيقات","lp.email_t":"البريد الإلكتروني","lp.site_t":"زوري الموقع الكامل","lp.site_s":"الخدمات والأسعار والسياسات","lp.foot":"اطلبي أي ماركة فيتنامية — بما في ذلك القطع غير المنشورة.<br>أسعار واضحة، ونصيحة صادقة في المقاس، وشحن إلى جميع أنحاء العالم من سايغون.","qe.eyebrow":"تقدير تقريبي","qe.title":"تقدير سريع","qe.sub":"تقدير تقريبي في ثوانٍ. بلا أي دفع — يُؤكَّد عرض السعر النهائي عند مراسلتك لي.","qe.budget":"ميزانية القطعة (USD)","qe.shipto":"الشحن إلى","qe.bulky":"قطعة ضخمة أو عدة قطع (طرد أثقل)","qe.rnote":"تقدير شامل · القطع + رسوم الخدمة + الشحن","qe.dm":"راسليني عبر Instagram","qe.email":"أرسلي هذا التقدير بالبريد","qe.copied":"✓ تم نسخ التقدير — ما عليك سوى لصقه في الرسالة الخاصة.","qe.full":"تفضّلين أداة التقدير المفصّلة؟ افتحي الموقع الكامل →","a11y.title":"الإعدادات","theme.mono":"أحادي"},
    "fr": {"lp.dir_t":"Le Répertoire de la Mode de Saïgon","lp.dir_s":"239 maisons vérifiées, cartographiées par district","lp.fg_t":"Le Guide de Terrain du Shopping à Saïgon","lp.fg_s":"Se déplacer, s'habiller pour la chaleur et des itinéraires de 1 à 30 jours","lp.houses_t":"Parcourir les maisons","lp.houses_s":"Touchez une marque pour l'ouvrir dans le répertoire","lp.trust":"Hô Chi Minh-Ville · Réponse sous 1 à 2 jours ouvrés","lp.estlink":"ou obtenez une estimation rapide →","lp.proof1":"Livraison dans le monde entier","lp.proof2":"Vérifié en personne","lp.proof3":"Conseils sincères sur la coupe","lp.order_t":"Commandez n'importe quelle marque vietnamienne","lp.order_s":"Même les pièces non publiées — envoyez-moi votre liste de souhaits","lp.est_t":"Obtenez une estimation rapide","lp.est_s":"Un ordre de grandeur en quelques secondes, puis écrivez-moi en DM ou par e-mail","lp.ig_s":"Trouvailles du jour et vidéos de coupe · @seraphicstyler","lp.tt_s":"Clips de stylisme et déballages · @seraphicstyler","lp.look_s":"Sourcing et stylisme récents","lp.email_t":"E-mail","lp.site_t":"Visitez le site complet","lp.site_s":"Services, tarifs et conditions","lp.foot":"Commandez n'importe quelle marque vietnamienne — y compris les pièces non publiées.<br>Tarifs clairs, conseils sincères sur la coupe et livraison dans le monde entier depuis Saïgon.","qe.eyebrow":"Estimation approximative","qe.title":"Estimation rapide","qe.sub":"Un ordre de grandeur en quelques secondes. Aucun paiement — votre devis final est confirmé lorsque vous m'écrivez.","qe.budget":"Budget de l'article (USD)","qe.shipto":"Livrer à","qe.bulky":"Article volumineux ou plusieurs articles (colis plus lourd)","qe.rnote":"estimation tout compris · articles + frais de service + livraison","qe.dm":"Écrivez-moi sur Instagram","qe.email":"Envoyer cette estimation par e-mail","qe.copied":"✓ Estimation copiée — il ne reste qu'à la coller dans le DM.","qe.full":"Vous préférez l'estimateur détaillé ? Ouvrez le site complet →","a11y.title":"Paramètres","theme.mono":"Mono"},
    "pt": {"lp.dir_t":"O Diretório de Moda de Saigão","lp.dir_s":"239 casas verificadas, mapeadas por distrito","lp.fg_t":"O Guia de Campo para Comprar em Saigão","lp.fg_s":"Como circular, como vestir-se no calor e itinerários de 1 a 30 dias","lp.houses_t":"Explore as casas","lp.houses_s":"Toque em qualquer marca para a abrir no diretório","lp.trust":"Cidade de Ho Chi Minh · Respondo em 1–2 dias úteis","lp.estlink":"ou receba uma estimativa rápida →","lp.proof1":"Envio para todo o mundo","lp.proof2":"Verificado pessoalmente","lp.proof3":"Conselho honesto de caimento","lp.order_t":"Encomende qualquer marca vietnamita","lp.order_s":"Mesmo peças não publicadas — envie-me a sua lista de desejos","lp.est_t":"Receba uma estimativa rápida","lp.est_s":"Um valor aproximado em segundos e depois envie-me uma DM ou e-mail","lp.ig_s":"Achados diários e vídeos de caimento · @seraphicstyler","lp.tt_s":"Clipes de styling e unboxings · @seraphicstyler","lp.look_s":"Sourcing e styling recentes","lp.email_t":"E-mail","lp.site_t":"Visite o site completo","lp.site_s":"Serviços, preços e políticas","lp.foot":"Encomende qualquer marca vietnamita — incluindo peças não publicadas.<br>Preços claros, conselho honesto de caimento e envio para todo o mundo a partir de Saigão.","qe.eyebrow":"Estimativa aproximada","qe.title":"Estimativa rápida","qe.sub":"Um valor aproximado em segundos. Sem pagamento — o seu orçamento final é confirmado quando me enviar uma mensagem.","qe.budget":"Orçamento do artigo (USD)","qe.shipto":"Enviar para","qe.bulky":"Volumoso ou vários artigos (encomenda mais pesada)","qe.rnote":"estimativa total · artigos + taxa de serviço + envio","qe.dm":"Enviar mensagem no Instagram","qe.email":"Enviar esta estimativa por e-mail","qe.copied":"✓ Estimativa copiada — basta colá-la na DM.","qe.full":"Prefere o estimador detalhado? Abra o site completo →","a11y.title":"Definições","theme.mono":"Mono"},
    "ru": {"lp.dir_t":"Каталог моды Сайгона","lp.dir_s":"239 проверенных лично домов, по районам","lp.fg_t":"Путеводитель по шопингу в Сайгоне","lp.fg_s":"Как передвигаться, как одеваться в жару и маршруты от 1 до 30 дней","lp.houses_t":"Смотреть дома моды","lp.houses_s":"Нажмите на любой логотип, чтобы открыть его в каталоге","lp.trust":"Хошимин · Отвечаю в течение 1–2 рабочих дней","lp.estlink":"или узнайте примерную стоимость →","lp.proof1":"Доставка по всему миру","lp.proof2":"Проверено лично","lp.proof3":"Честный совет по посадке","lp.order_t":"Заказ любого вьетнамского бренда","lp.order_s":"Даже вещи, которых нет в публикациях — пришлите мне свой вишлист","lp.est_t":"Узнайте примерную стоимость","lp.est_s":"Ориентировочная сумма за секунды, затем напишите мне в директ или на почту","lp.ig_s":"Ежедневные находки и видео о посадке · @seraphicstyler","lp.tt_s":"Ролики о стиле и распаковки · @seraphicstyler","lp.look_s":"Недавние находки и образы","lp.email_t":"Эл. почта","lp.site_t":"Перейти на полный сайт","lp.site_s":"Услуги, цены и условия","lp.foot":"Заказ любого вьетнамского бренда — включая вещи, которых нет в публикациях.<br>Прозрачные цены, честный совет по посадке и доставка по всему миру из Сайгона.","qe.eyebrow":"Примерный расчёт","qe.title":"Быстрая оценка","qe.sub":"Ориентировочная сумма за секунды. Без оплаты — окончательная цена подтверждается, когда вы мне напишете.","qe.budget":"Бюджет на вещь (USD)","qe.shipto":"Доставка в","qe.bulky":"Габаритные или несколько вещей (более тяжёлая посылка)","qe.rnote":"оценка «всё включено» · вещи + сервисный сбор + доставка","qe.dm":"Написать в Instagram","qe.email":"Отправить эту оценку по почте","qe.copied":"✓ Оценка скопирована — просто вставьте её в сообщение.","qe.full":"Предпочитаете подробный расчёт? Откройте полный сайт →","a11y.title":"Настройки","theme.mono":"Моно"},
    "ja": {"lp.dir_t":"サイゴンファッションディレクトリ","lp.dir_s":"実際に確かめた239軒を、地区ごとに","lp.fg_t":"サイゴン買い物フィールドガイド","lp.fg_s":"移動の仕方、暑さに合う装い、1日から30日までの旅程","lp.houses_t":"ブランドを見る","lp.houses_s":"ロゴをタップすると、ディレクトリで開きます","lp.trust":"ホーチミン市 · 1〜2営業日以内にご返信します","lp.estlink":"または、すぐにお見積もりを →","lp.proof1":"世界中へ発送","lp.proof2":"現物を直接確認","lp.proof3":"サイズ感は正直にアドバイス","lp.order_t":"ベトナムのどんなブランドもご注文を","lp.order_s":"掲載していないアイテムも、ご希望のリストをお送りください","lp.est_t":"すぐにお見積もりを","lp.est_s":"数秒で概算が分かります。その後、DMまたはメールでご連絡ください","lp.ig_s":"日々の見つけものとサイズ感の動画 · @seraphicstyler","lp.tt_s":"スタイリング動画と開封の様子 · @seraphicstyler","lp.look_s":"最近のお取り寄せとスタイリング","lp.email_t":"メール","lp.site_t":"公式サイトを見る","lp.site_s":"サービス・料金・ポリシー","lp.foot":"ベトナムのどんなブランドもご注文いただけます — 掲載していないアイテムも含めて。<br>明朗な料金、正直なサイズ感のアドバイス、そしてサイゴンから世界中への発送を。","qe.eyebrow":"おおよその概算","qe.title":"かんたん見積もり","qe.sub":"数秒で概算が分かります。お支払いは不要 — 正式なお見積もりは、ご連絡いただいた際に確定します。","qe.budget":"アイテムの予算（USD）","qe.shipto":"お届け先","qe.bulky":"かさばる、または複数のアイテム（重めの荷物）","qe.rnote":"すべて込みの概算 · 商品代 + サービス料 + 送料","qe.dm":"Instagramでメッセージを送る","qe.email":"この見積もりをメールで送る","qe.copied":"✓ 見積もりをコピーしました — そのままDMに貼り付けてください。","qe.full":"より詳しい見積もりをご希望ですか？ 公式サイトを開く →","a11y.title":"設定","theme.mono":"モノ"},
    "de": {"lp.dir_t":"Das Saigoner Mode-Verzeichnis","lp.dir_s":"239 persönlich geprüfte Häuser, nach Bezirk geordnet","lp.fg_t":"Der Feldführer fürs Shoppen in Saigon","lp.fg_s":"Unterwegs sein, sich für die Hitze kleiden und Routen von 1 bis 30 Tagen","lp.houses_t":"Die Häuser durchstöbern","lp.houses_s":"Tippen Sie auf ein Label, um es im Verzeichnis zu öffnen","lp.trust":"Ho-Chi-Minh-Stadt · Antwort innerhalb von 1–2 Werktagen","lp.estlink":"oder schnell einen Richtwert erhalten →","lp.proof1":"Weltweiter Versand","lp.proof2":"Persönlich geprüft","lp.proof3":"Ehrliche Passform-Beratung","lp.order_t":"Jede vietnamesische Marke bestellen","lp.order_s":"Auch nicht gepostete Stücke – schicken Sie mir Ihre Wunschliste","lp.est_t":"Schnellen Richtwert erhalten","lp.est_s":"In Sekunden ein Richtwert, dann per DM oder E-Mail an mich","lp.ig_s":"Tägliche Funde & Passform-Videos · @seraphicstyler","lp.tt_s":"Styling-Clips & Unboxings · @seraphicstyler","lp.look_s":"Aktuelle Beschaffungen & Styling","lp.email_t":"E-Mail","lp.site_t":"Zur kompletten Website","lp.site_s":"Leistungen, Preise & Richtlinien","lp.foot":"Bestellen Sie jede vietnamesische Marke – auch nicht gepostete Stücke.<br>Klare Preise, ehrliche Passform-Beratung und weltweiter Versand aus Saigon.","qe.eyebrow":"Ungefährer Richtwert","qe.title":"Schneller Richtwert","qe.sub":"In Sekunden ein Richtwert. Keine Zahlung – Ihr endgültiges Angebot wird bestätigt, sobald Sie mir schreiben.","qe.budget":"Budget pro Stück (USD)","qe.shipto":"Versand nach","qe.bulky":"Sperrig oder mehrere Stücke (schwereres Paket)","qe.rnote":"All-inclusive-Richtwert · Artikel + Servicegebühr + Versand","qe.dm":"Auf Instagram schreiben","qe.email":"Diesen Richtwert per E-Mail senden","qe.copied":"✓ Richtwert kopiert – einfach in die DM einfügen.","qe.full":"Lieber der detaillierte Rechner? Zur kompletten Website →","a11y.title":"Einstellungen","theme.mono":"Mono"},
    "ko": {"lp.dir_t":"사이공 패션 디렉터리","lp.dir_s":"직접 확인한 239곳, 구별로 정리했어요","lp.fg_t":"사이공 쇼핑 필드 가이드","lp.fg_s":"이동하는 법, 더위에 맞는 옷차림, 그리고 1일에서 30일까지의 일정","lp.houses_t":"브랜드 둘러보기","lp.houses_s":"로고를 누르면 디렉터리에서 열려요","lp.trust":"호치민시 · 영업일 기준 1~2일 내 답변드려요","lp.estlink":"또는 간편 견적 받아보기 →","lp.proof1":"전 세계 배송","lp.proof2":"직접 검수 완료","lp.proof3":"솔직한 핏 조언","lp.order_t":"모든 베트남 브랜드 주문 가능","lp.order_s":"게시되지 않은 제품도 괜찮아요 — 위시리스트를 보내주세요","lp.est_t":"간편 견적 받기","lp.est_s":"몇 초 만에 대략적인 금액을, 그 후 DM이나 이메일로 연락 주세요","lp.ig_s":"매일의 발견과 핏 영상 · @seraphicstyler","lp.tt_s":"스타일링 클립과 언박싱 · @seraphicstyler","lp.look_s":"최근 소싱과 스타일링","lp.email_t":"이메일","lp.site_t":"전체 사이트 방문하기","lp.site_s":"서비스, 가격 및 정책","lp.foot":"게시되지 않은 제품을 포함해 모든 베트남 브랜드를 주문해 드려요.<br>투명한 가격, 솔직한 핏 조언, 그리고 사이공에서의 전 세계 배송.","qe.eyebrow":"대략적인 견적","qe.title":"간편 견적","qe.sub":"몇 초 만에 대략적인 금액을. 결제는 없어요 — 최종 견적은 메시지를 주시면 확정해 드려요.","qe.budget":"제품 예산 (USD)","qe.shipto":"배송지","qe.bulky":"부피가 크거나 여러 제품 (무거운 소포)","qe.rnote":"총 견적 · 제품 + 서비스 수수료 + 배송비","qe.dm":"Instagram으로 메시지 보내기","qe.email":"이 견적을 이메일로 보내기","qe.copied":"✓ 견적이 복사되었어요 — DM에 붙여넣기만 하시면 돼요.","qe.full":"상세 견적 도구를 원하시나요? 전체 사이트 열기 →","a11y.title":"설정","theme.mono":"모노"},
    "hi": {"lp.dir_t":"साइगॉन फ़ैशन डायरेक्टरी","lp.dir_s":"239 जाँची-परखी दुकानें, ज़िले के हिसाब से","lp.fg_t":"साइगॉन शॉपिंग फ़ील्ड गाइड","lp.fg_s":"कैसे घूमें, गर्मी में क्या पहनें, और 1 से 30 दिन तक की योजनाएँ","lp.houses_t":"दुकानें देखें","lp.houses_s":"किसी भी लेबल पर टैप करें, वह डायरेक्टरी में खुलेगा","lp.trust":"हो ची मिन्ह सिटी · 1–2 कार्यदिवसों में उत्तर","lp.estlink":"या एक झटपट अनुमान पाएँ →","lp.proof1":"दुनिया भर में शिपिंग","lp.proof2":"स्वयं जाँची-परखी","lp.proof3":"ईमानदार फ़िट सलाह","lp.order_t":"कोई भी वियतनामी ब्रांड मँगवाएँ","lp.order_s":"जो टुकड़े पोस्ट नहीं किए, वे भी — अपनी विशलिस्ट भेजें","lp.est_t":"एक झटपट अनुमान पाएँ","lp.est_s":"कुछ ही पलों में अंदाज़ा, फिर मुझे DM या ईमेल करें","lp.ig_s":"रोज़ाना की खोज और फ़िट वीडियो · @seraphicstyler","lp.tt_s":"स्टाइलिंग क्लिप और अनबॉक्सिंग · @seraphicstyler","lp.look_s":"हाल की सोर्सिंग और स्टाइलिंग","lp.email_t":"ईमेल","lp.site_t":"पूरी साइट देखें","lp.site_s":"सेवाएँ, मूल्य और नीतियाँ","lp.foot":"कोई भी वियतनामी ब्रांड मँगवाएँ — वे टुकड़े भी जो पोस्ट नहीं किए गए।<br>साफ़ मूल्य, ईमानदार फ़िट सलाह, और साइगॉन से दुनिया भर में शिपिंग।","qe.eyebrow":"मोटा-मोटी अनुमान","qe.title":"झटपट अनुमान","qe.sub":"कुछ ही पलों में अंदाज़ा। कोई भुगतान नहीं — आपका अंतिम कोट तब पक्का होता है जब आप मुझे संदेश भेजते हैं।","qe.budget":"वस्तु बजट (USD)","qe.shipto":"कहाँ भेजना है","qe.bulky":"भारी या कई वस्तुएँ (वज़नी पार्सल)","qe.rnote":"सब-कुछ शामिल अनुमान · वस्तुएँ + सेवा शुल्क + शिपिंग","qe.dm":"Instagram पर संदेश भेजें","qe.email":"यह अनुमान ईमेल करें","qe.copied":"✓ अनुमान कॉपी हो गया — बस इसे DM में पेस्ट कर दें।","qe.full":"विस्तृत अनुमानक पसंद है? पूरी साइट खोलें →","a11y.title":"सेटिंग्स","theme.mono":"मोनो"},
    "id": {"lp.dir_t":"Direktori Mode Saigon","lp.dir_s":"239 rumah mode terverifikasi, dipetakan per distrik","lp.fg_t":"Panduan Lapangan Belanja di Saigon","lp.fg_s":"Cara berkeliling, berpakaian di tengah panas, dan itinerari 1 hingga 30 hari","lp.houses_t":"Jelajahi rumah modenya","lp.houses_s":"Ketuk label mana pun untuk membukanya di direktori","lp.trust":"Kota Ho Chi Minh · Membalas dalam 1–2 hari kerja","lp.estlink":"atau dapatkan perkiraan cepat →","lp.proof1":"Pengiriman ke seluruh dunia","lp.proof2":"Diverifikasi langsung","lp.proof3":"Saran kecocokan yang jujur","lp.order_t":"Pesan merek Vietnam apa pun","lp.order_s":"Bahkan yang belum diunggah — kirimkan daftar keinginan Anda","lp.est_t":"Dapatkan perkiraan cepat","lp.est_s":"Perkiraan kasar dalam hitungan detik, lalu DM atau email saya","lp.ig_s":"Temuan harian & video kecocokan · @seraphicstyler","lp.tt_s":"Klip styling & unboxing · @seraphicstyler","lp.look_s":"Sumber & styling terbaru","lp.email_t":"Email","lp.site_t":"Kunjungi situs lengkap","lp.site_s":"Layanan, harga & kebijakan","lp.foot":"Pesan merek Vietnam apa pun — termasuk yang belum diunggah.<br>Harga jelas, saran kecocokan yang jujur, dan pengiriman ke seluruh dunia dari Saigon.","qe.eyebrow":"Perkiraan kasar","qe.title":"Perkiraan cepat","qe.sub":"Perkiraan kasar dalam hitungan detik. Tanpa pembayaran — penawaran akhir Anda dikonfirmasi saat Anda mengirim pesan kepada saya.","qe.budget":"Anggaran barang (USD)","qe.shipto":"Kirim ke","qe.bulky":"Barang besar atau beberapa item (paket lebih berat)","qe.rnote":"perkiraan menyeluruh · barang + biaya layanan + pengiriman","qe.dm":"Kirim pesan di Instagram","qe.email":"Email perkiraan ini","qe.copied":"✓ Perkiraan disalin — tinggal tempel ke dalam DM.","qe.full":"Lebih suka estimator terperinci? Buka situs lengkap →","a11y.title":"Pengaturan","theme.mono":"Mono"},
    "th": {"lp.dir_t":"ไดเรกทอรีแฟชั่นไซ่ง่อน","lp.dir_s":"239 ร้านที่ไปดูมาเอง จัดตามเขต","lp.fg_t":"คู่มือภาคสนามสำหรับช้อปปิ้งในไซ่ง่อน","lp.fg_s":"การเดินทาง การแต่งตัวรับอากาศร้อน และแผนเที่ยว 1 ถึง 30 วัน","lp.houses_t":"เลือกดูร้านต่างๆ","lp.houses_s":"แตะโลโก้ใดก็ได้เพื่อเปิดในไดเรกทอรี","lp.trust":"นครโฮจิมินห์ · ตอบกลับภายใน 1–2 วันทำการ","lp.estlink":"หรือขอประเมินราคาคร่าวๆ →","lp.proof1":"จัดส่งทั่วโลก","lp.proof2":"ตรวจสอบด้วยตนเอง","lp.proof3":"คำแนะนำเรื่องไซซ์ที่ตรงไปตรงมา","lp.order_t":"สั่งสินค้าแบรนด์เวียดนามได้ทุกแบรนด์","lp.order_s":"แม้แต่ชิ้นที่ไม่ได้ลงไว้ — ส่งลิสต์ที่อยากได้มาให้ฉันได้เลย","lp.est_t":"ขอประเมินราคาคร่าวๆ","lp.est_s":"ได้ตัวเลขคร่าวๆ ในไม่กี่วินาที แล้วทักหรืออีเมลมาหาฉัน","lp.ig_s":"ของน่าช้อปและวิดีโอลองใส่ทุกวัน · @seraphicstyler","lp.tt_s":"คลิปจัดสไตล์และแกะกล่อง · @seraphicstyler","lp.look_s":"งานจัดหาและจัดสไตล์ล่าสุด","lp.email_t":"อีเมล","lp.site_t":"เยี่ยมชมเว็บไซต์ฉบับเต็ม","lp.site_s":"บริการ ราคา และเงื่อนไข","lp.foot":"สั่งสินค้าแบรนด์เวียดนามได้ทุกแบรนด์ — รวมถึงชิ้นที่ไม่ได้ลงไว้<br>ราคาชัดเจน คำแนะนำเรื่องไซซ์ที่ตรงไปตรงมา และจัดส่งทั่วโลกจากไซง่อน","qe.eyebrow":"ประเมินคร่าวๆ","qe.title":"ประเมินราคาด่วน","qe.sub":"ได้ตัวเลขคร่าวๆ ในไม่กี่วินาที ไม่ต้องชำระเงิน — ราคาสุดท้ายจะยืนยันเมื่อคุณทักมาหาฉัน","qe.budget":"งบต่อชิ้น (USD)","qe.shipto":"จัดส่งไปยัง","qe.bulky":"ชิ้นใหญ่หรือหลายชิ้น (พัสดุน้ำหนักมาก)","qe.rnote":"ประเมินแบบรวมทุกอย่าง · ค่าสินค้า + ค่าบริการ + ค่าจัดส่ง","qe.dm":"ทักมาทาง Instagram","qe.email":"ส่งราคาประเมินนี้ทางอีเมล","qe.copied":"✓ คัดลอกราคาประเมินแล้ว — แค่วางลงในข้อความ DM","qe.full":"อยากได้เครื่องมือประเมินแบบละเอียดใช่ไหม เปิดเว็บไซต์ฉบับเต็ม →","a11y.title":"การตั้งค่า","theme.mono":"โมโน"},
    "it": {"lp.dir_t":"L'elenco della Moda di Saigon","lp.dir_s":"239 case verificate di persona, mappate per distretto","lp.fg_t":"La Guida sul Campo allo Shopping a Saigon","lp.fg_s":"Come muoversi, come vestirsi con il caldo e itinerari da 1 a 30 giorni","lp.houses_t":"Sfoglia le case","lp.houses_s":"Tocca un marchio per aprirlo nell'elenco","lp.trust":"Ho Chi Minh City · Rispondo entro 1–2 giorni lavorativi","lp.estlink":"oppure ottieni un preventivo rapido →","lp.proof1":"Spedizione in tutto il mondo","lp.proof2":"Verificato di persona","lp.proof3":"Consigli sinceri sulla vestibilità","lp.order_t":"Ordina qualsiasi marca vietnamita","lp.order_s":"Anche i capi non pubblicati — inviami la tua wishlist","lp.est_t":"Ottieni un preventivo rapido","lp.est_s":"Una stima in pochi secondi, poi scrivimi in DM o via email","lp.ig_s":"Trovate quotidiane e video di vestibilità · @seraphicstyler","lp.tt_s":"Clip di styling e unboxing · @seraphicstyler","lp.look_s":"Ultime ricerche e styling","lp.email_t":"Email","lp.site_t":"Visita il sito completo","lp.site_s":"Servizi, prezzi e condizioni","lp.foot":"Ordina qualsiasi marca vietnamita — inclusi i capi non pubblicati.<br>Prezzi chiari, consigli sinceri sulla vestibilità e spedizione in tutto il mondo da Saigon.","qe.eyebrow":"Stima approssimativa","qe.title":"Preventivo rapido","qe.sub":"Una stima in pochi secondi. Nessun pagamento — il preventivo definitivo viene confermato quando mi scrivi.","qe.budget":"Budget per articolo (USD)","qe.shipto":"Spedire a","qe.bulky":"Articolo voluminoso o più articoli (pacco più pesante)","qe.rnote":"stima tutto incluso · articoli + commissione di servizio + spedizione","qe.dm":"Scrivimi su Instagram","qe.email":"Invia questo preventivo via email","qe.copied":"✓ Preventivo copiato — incollalo semplicemente nel DM.","qe.full":"Preferisci il calcolatore dettagliato? Apri il sito completo →","a11y.title":"Impostazioni","theme.mono":"Mono"},
    "tr": {"lp.dir_t":"Saigon Moda Rehberi","lp.dir_s":"Yerinde doğrulanmış 239 marka, semt semt","lp.fg_t":"Saigon Alışveriş Saha Rehberi","lp.fg_s":"Şehirde dolaşmak, sıcağa göre giyinmek ve 1 ila 30 günlük rotalar","lp.houses_t":"Markalara göz atın","lp.houses_s":"Herhangi bir logoya dokunun, rehberde açılsın","lp.trust":"Ho Chi Minh Şehri · 1–2 iş günü içinde yanıt","lp.estlink":"veya hızlı bir tahmin alın →","lp.proof1":"Dünya geneline gönderim","lp.proof2":"Bizzat doğrulanır","lp.proof3":"Dürüst kalıp önerisi","lp.order_t":"Her Vietnam markasını sipariş edin","lp.order_s":"Paylaşmadığım parçalar bile — istek listenizi bana gönderin","lp.est_t":"Hızlı bir tahmin alın","lp.est_s":"Saniyeler içinde yaklaşık bir rakam, ardından bana DM ya da e-posta gönderin","lp.ig_s":"Günlük keşifler ve kalıp videoları · @seraphicstyler","lp.tt_s":"Stil klipleri ve kutu açılışları · @seraphicstyler","lp.look_s":"Son tedarikler ve stil çalışmaları","lp.email_t":"E-posta","lp.site_t":"Tüm siteyi ziyaret edin","lp.site_s":"Hizmetler, fiyatlandırma ve koşullar","lp.foot":"Her Vietnam markasını sipariş edin — paylaşmadığım parçalar dahil.<br>Net fiyatlandırma, dürüst kalıp önerisi ve Saygon'dan dünya geneline gönderim.","qe.eyebrow":"Kabaca tahmin","qe.title":"Hızlı tahmin","qe.sub":"Saniyeler içinde yaklaşık bir rakam. Ödeme yok — kesin fiyatınız bana mesaj attığınızda onaylanır.","qe.budget":"Ürün bütçesi (USD)","qe.shipto":"Gönderim yeri","qe.bulky":"Hacimli ya da birden fazla ürün (daha ağır koli)","qe.rnote":"her şey dahil tahmin · ürünler + hizmet ücreti + gönderim","qe.dm":"Instagram'dan mesaj gönderin","qe.email":"Bu tahmini e-postayla gönderin","qe.copied":"✓ Tahmin kopyalandı — DM'e yapıştırmanız yeterli.","qe.full":"Ayrıntılı tahmin aracını mı tercih edersiniz? Tüm siteyi açın →","a11y.title":"Ayarlar","theme.mono":"Mono"},
    "tl": {"lp.dir_t":"Ang Direktoryo ng Fashion sa Saigon","lp.dir_s":"239 na bahay-modang personal na sinuri, ayon sa distrito","lp.fg_t":"Ang Field Guide sa Pamimili sa Saigon","lp.fg_s":"Paano maglibot, magdamit sa init, at mga itinerary mula 1 hanggang 30 araw","lp.houses_t":"Tingnan ang mga bahay-moda","lp.houses_s":"I-tap ang alinmang label para buksan ito sa direktoryo","lp.trust":"Ho Chi Minh City · Tumutugon sa loob ng 1–2 araw ng negosyo","lp.estlink":"o kumuha ng mabilis na pagtatantya →","lp.proof1":"Nagpapadala sa buong mundo","lp.proof2":"Personal na sinuri","lp.proof3":"Tapat na payo sa pagkakasukat","lp.order_t":"Mag-order ng anumang brand mula sa Vietnam","lp.order_s":"Kahit mga piyesang hindi naka-post — ipadala sa akin ang iyong wishlist","lp.est_t":"Kumuha ng mabilis na pagtatantya","lp.est_s":"Tantiyang halaga sa ilang segundo, tapos i-DM o i-email ako","lp.ig_s":"Pang-araw-araw na natuklasan at fit videos · @seraphicstyler","lp.tt_s":"Mga styling clip at unboxing · @seraphicstyler","lp.look_s":"Mga kamakailang sinourcing at styling","lp.email_t":"Email","lp.site_t":"Bisitahin ang buong site","lp.site_s":"Mga serbisyo, presyo at patakaran","lp.foot":"Mag-order ng anumang brand mula sa Vietnam — kasama ang mga piyesang hindi naka-post.<br>Malinaw na presyo, tapat na payo sa pagkakasukat, at pagpapadala sa buong mundo mula sa Saigon.","qe.eyebrow":"Pangkalahatang tantiya","qe.title":"Mabilis na pagtatantya","qe.sub":"Tantiyang halaga sa ilang segundo. Walang bayad — ang iyong panghuling quote ay kumpirmado kapag nag-message ka sa akin.","qe.budget":"Budget para sa item (USD)","qe.shipto":"Ipadala sa","qe.bulky":"Malaki o maraming item (mas mabigat na parcel)","qe.rnote":"all-in na tantiya · mga item + service fee + pagpapadala","qe.dm":"Mag-message sa Instagram","qe.email":"I-email ang tantiyang ito","qe.copied":"✓ Nakopya ang tantiya — i-paste na lang ito sa DM.","qe.full":"Mas gusto ang detalyadong estimator? Buksan ang buong site →","a11y.title":"Mga Setting","theme.mono":"Mono"},
    "pl": {"lp.dir_t":"Katalog Mody Sajgonu","lp.dir_s":"239 osobiście sprawdzonych domów mody, według dzielnic","lp.fg_t":"Przewodnik po zakupach w Sajgonie","lp.fg_s":"Jak się poruszać, jak ubrać się w upale i plany od 1 do 30 dni","lp.houses_t":"Przejrzyj domy mody","lp.houses_s":"Dotknij dowolnego logo, aby otworzyć je w katalogu","lp.trust":"Ho Chi Minh City · Odpowiadam w ciągu 1–2 dni roboczych","lp.estlink":"lub uzyskaj szybką wycenę →","lp.proof1":"Wysyłka na cały świat","lp.proof2":"Sprawdzone osobiście","lp.proof3":"Szczere porady dotyczące dopasowania","lp.order_t":"Zamów dowolną wietnamską markę","lp.order_s":"Nawet rzeczy, których nie pokazałam — prześlij mi swoją listę życzeń","lp.est_t":"Uzyskaj szybką wycenę","lp.est_s":"Orientacyjna kwota w kilka sekund, a potem napisz do mnie wiadomość lub e-mail","lp.ig_s":"Codzienne znaleziska i filmy z dopasowania · @seraphicstyler","lp.tt_s":"Klipy stylizacyjne i rozpakowania · @seraphicstyler","lp.look_s":"Ostatnie znaleziska i stylizacje","lp.email_t":"E-mail","lp.site_t":"Odwiedź pełną stronę","lp.site_s":"Usługi, cennik i zasady","lp.foot":"Zamów dowolną wietnamską markę — w tym rzeczy, których nie pokazałam.<br>Przejrzyste ceny, szczere porady dotyczące dopasowania i wysyłka na cały świat z Sajgonu.","qe.eyebrow":"Wstępna wycena","qe.title":"Szybka wycena","qe.sub":"Orientacyjna kwota w kilka sekund. Bez płatności — ostateczną wycenę potwierdzam, gdy napiszesz do mnie wiadomość.","qe.budget":"Budżet na rzecz (USD)","qe.shipto":"Wysyłka do","qe.bulky":"Duże gabarytowo lub kilka rzeczy (cięższa paczka)","qe.rnote":"wycena całkowita · rzeczy + opłata za usługę + wysyłka","qe.dm":"Napisz na Instagramie","qe.email":"Wyślij tę wycenę e-mailem","qe.copied":"✓ Wycena skopiowana — po prostu wklej ją w wiadomości.","qe.full":"Wolisz szczegółowy kalkulator? Otwórz pełną stronę →","a11y.title":"Ustawienia","theme.mono":"Mono"},
    "nl": {"lp.dir_t":"De Modegids van Saigon","lp.dir_s":"239 persoonlijk geverifieerde huizen, per district","lp.fg_t":"De Veldgids voor Shoppen in Saigon","lp.fg_s":"Je verplaatsen, je kleden in de hitte en routes van 1 tot 30 dagen","lp.houses_t":"Blader door de huizen","lp.houses_s":"Tik op een label om het in de gids te openen","lp.trust":"Ho Chi Minhstad · Antwoord binnen 1–2 werkdagen","lp.estlink":"of ontvang snel een schatting →","lp.proof1":"Wereldwijde verzending","lp.proof2":"Persoonlijk geverifieerd","lp.proof3":"Eerlijk pasvormadvies","lp.order_t":"Bestel elk Vietnamees merk","lp.order_s":"Ook stukken die niet geplaatst zijn — stuur me je verlanglijst","lp.est_t":"Ontvang snel een schatting","lp.est_s":"In enkele seconden een indicatie, daarna stuur je me een DM of e-mail","lp.ig_s":"Dagelijkse vondsten & pasvormvideo's · @seraphicstyler","lp.tt_s":"Stylingclips & unboxings · @seraphicstyler","lp.look_s":"Recente vondsten & styling","lp.email_t":"E-mail","lp.site_t":"Bezoek de volledige site","lp.site_s":"Diensten, prijzen & voorwaarden","lp.foot":"Bestel elk Vietnamees merk — ook stukken die niet geplaatst zijn.<br>Heldere prijzen, eerlijk pasvormadvies en wereldwijde verzending vanuit Saigon.","qe.eyebrow":"Ruwe schatting","qe.title":"Snelle schatting","qe.sub":"In enkele seconden een indicatie. Geen betaling — je definitieve offerte wordt bevestigd zodra je me een bericht stuurt.","qe.budget":"Budget per stuk (USD)","qe.shipto":"Verzenden naar","qe.bulky":"Volumineus of meerdere stuks (zwaarder pakket)","qe.rnote":"all-in schatting · stuks + servicekosten + verzending","qe.dm":"Bericht sturen op Instagram","qe.email":"Deze schatting e-mailen","qe.copied":"✓ Schatting gekopieerd — plak deze gewoon in de DM.","qe.full":"Liever de gedetailleerde calculator? Open de volledige site →","a11y.title":"Instellingen","theme.mono":"Mono"},
    "fa": {"lp.dir_t":"فهرست مد سایگون","lp.dir_s":"239 خانهٔ مد که خودم بررسی کرده‌ام، به تفکیک منطقه","lp.fg_t":"راهنمای میدانی خرید در سایگون","lp.fg_s":"رفت‌وآمد، لباس پوشیدن در گرما، و برنامه‌های 1 تا 30 روزه","lp.houses_t":"خانه‌های مد را ببینید","lp.houses_s":"روی هر نشان بزنید تا در فهرست باز شود","lp.trust":"هوشی‌مین · پاسخ ظرف ۱ تا ۲ روز کاری","lp.estlink":"یا یک برآورد سریع بگیرید →","lp.proof1":"ارسال به سراسر جهان","lp.proof2":"بررسی‌شده به‌صورت حضوری","lp.proof3":"مشاورهٔ صادقانه دربارهٔ اندازه","lp.order_t":"سفارش هر برند ویتنامی","lp.order_s":"حتی قطعاتی که منتشر نشده‌اند — فهرست خواسته‌هایتان را برایم بفرستید","lp.est_t":"یک برآورد سریع بگیرید","lp.est_s":"تخمینی تقریبی در چند ثانیه، سپس در دایرکت یا ایمیل به من پیام دهید","lp.ig_s":"یافته‌های روزانه و ویدیوهای اندازه · @seraphicstyler","lp.tt_s":"کلیپ‌های استایلینگ و آنباکسینگ · @seraphicstyler","lp.look_s":"تأمین و استایلینگ‌های اخیر","lp.email_t":"ایمیل","lp.site_t":"بازدید از سایت کامل","lp.site_s":"خدمات، قیمت‌گذاری و قوانین","lp.foot":"سفارش هر برند ویتنامی — از جمله قطعاتی که منتشر نشده‌اند.<br>قیمت‌گذاری شفاف، مشاورهٔ صادقانه دربارهٔ اندازه، و ارسال به سراسر جهان از سایگون.","qe.eyebrow":"برآورد تقریبی","qe.title":"برآورد سریع","qe.sub":"تخمینی تقریبی در چند ثانیه. بدون پرداخت — قیمت نهایی شما هنگام پیام دادن به من تأیید می‌شود.","qe.budget":"بودجهٔ کالا (USD)","qe.shipto":"ارسال به","qe.bulky":"حجیم یا چند قلم (بستهٔ سنگین‌تر)","qe.rnote":"برآورد کلی · کالاها + هزینهٔ خدمات + ارسال","qe.dm":"پیام در Instagram","qe.email":"ارسال این برآورد با ایمیل","qe.copied":"✓ برآورد کپی شد — کافی است آن را در دایرکت بچسبانید.","qe.full":"برآوردگر دقیق‌تر را ترجیح می‌دهید؟ سایت کامل را باز کنید →","a11y.title":"تنظیمات","theme.mono":"Mono"},
  };
  Object.keys(add).forEach(function (l) {
    T[l] = T[l] || {};
    var m = add[l];
    for (var k in m) { if (Object.prototype.hasOwnProperty.call(m, k)) T[l][k] = m[k]; }
  });
})();
