/* Generated by tools/i18n/validate-build.js — do not edit.
   Languages with a validated bundle, per page. The selector shows only these. */
window.SS_I18N_AVAILABLE={"fd":["vi","zh","es","ar","fr","pt","ru","ja","de","ko","hi","id","th","it","tr","tl","pl","nl","fa","zgh"],"fg":["vi","zh","es","ar","fr","pt","ru","ja","de","ko","hi","id","th","it","tr","tl","pl","nl","fa","zgh"]};
